# A+aron: VCT Mindfreak


## Step 0: Define Target & Load Data
Since we're doing match wins rather than series wins, we have to define what each win or loss looks like. For example, PRX will win is defined by binary 1 and G2 will lose is defined by binary 0.

And we have to load in all the data to be used in this step.

**Adding new seasons (e.g. 2026):** drop a `vct_2026/` folder next to the others, matching the same
subfolder layout (`matches/`, `players_stats/`, `agents/`, `ids/`).


In [ ]:
# ==========SHARED CONFIG: DATA YEARS & LOADER HELPERS==========

import glob
import os
import re

root_path = "./"

def get_available_years(root=root_path):
    """Auto-detect which vct_YYYY folders exist on disk, sorted ascending."""
    found = []
    for path in glob.glob(os.path.join(root, "vct_*")):
        m = re.fullmatch(r"vct_(\d{4})", os.path.basename(path))
        if m:
            found.append(int(m.group(1)))
    return sorted(found)

DATA_YEARS = get_available_years()
# Version tag used to name every combined output CSV, e.g. "2021_2026"
DATA_VERSION = f"{DATA_YEARS[0]}_{DATA_YEARS[-1]}" if DATA_YEARS else "unknown"

print(f"Detected seasons: {DATA_YEARS}")
print(f"DATA_VERSION tag for output files: {DATA_VERSION}")


def load_years_csv(relative_path_template, years=DATA_YEARS, root=root_path, per_year_fn=None):
    """
    Load and concat a per-year CSV across all detected seasons.

    relative_path_template: e.g. "vct_{year}/matches/maps_scores.csv"
    per_year_fn: optional function(df, year) -> df applied to each year's data
                 (for per-file cleanup) before concatenation.
    Missing files (e.g. a season folder that doesn't have every file yet,
    such as a still-in-progress 2026) are skipped with a printed note instead
    of raising, so partial new-season data never breaks this step.
    """
    import pandas as pd
    frames = []
    for year in years:
        file_path = os.path.join(root, relative_path_template.format(year=year))
        if not os.path.exists(file_path):
            print(f"  [skip] {file_path} not found yet")
            continue
        df = pd.read_csv(file_path)
        df["Year"] = year
        if per_year_fn is not None:
            df = per_year_fn(df, year)
        frames.append(df)
    if not frames:
        raise FileNotFoundError(f"No files found for template: {relative_path_template}")
    return pd.concat(frames, ignore_index=True)


Detected seasons: [2021, 2022, 2023, 2024, 2025]
DATA_VERSION tag for output files: 2021_2025


In [2]:
# Installations
!pip install matplotlib
!pip install scikit-learn
!pip install lightgbm

In [ ]:
import pandas as pd
import numpy as np

# Uses DATA_YEARS detected in the shared config cell above.

# Columns to drop
drop_cols = [
    'Team A Attacker Score',
    'Team A Defender Score',
    'Team A Overtime Score',
    'Team B Attacker Score',
    'Team B Defender Score',
    'Team B Overtime Score'
]

matches = []

for year in DATA_YEARS:
    path = os.path.join(root_path, f"vct_{year}/matches/maps_scores.csv")
    if not os.path.exists(path):
        print(f"  [skip] {path} not found yet")
        continue
    df = pd.read_csv(path)

    df = df.drop(columns=drop_cols, errors='ignore')

    # Compute wins if not already done
    df['team_a_win'] = (df['Team A Score'] > df['Team B Score']).astype(int)
    df['team_b_win'] = (df['Team B Score'] > df['Team A Score']).astype(int)

    # Convert to long format
    df_long = pd.concat([
        df.assign(team=df['Team A'],
                  score=df['Team A Score'],
                  opponent=df['Team B'],
                  opponent_score=df['Team B Score'],
                  win=df['team_a_win']),
        df.assign(team=df['Team B'],
                  score=df['Team B Score'],
                  opponent=df['Team A'],
                  opponent_score=df['Team A Score'],
                  win=df['team_b_win'])
    ], ignore_index=True)

    # Add year/tournament column if needed
    df_long['Year'] = year

    matches.append(df_long)

# Combine all years
all_matches = pd.concat(matches, ignore_index=True)
matches[0].head()


,Tournament,Stage,Match Type,Match Name,Map,Team A,Team A Score,Team B,Team B Score,Duration,team_a_win,team_b_win,team,score,opponent,opponent_score,win,Year
0,Valorant Champions 2021,Group Stage,Opening (D),Vision Strikers vs FULL SENSE,Haven,Vision Strikers,13,FULL SENSE,5,59:11,1,0,Vision Strikers,13,FULL SENSE,5,1,2021
1,Valorant Champions 2021,Group Stage,Opening (D),Vision Strikers vs FULL SENSE,Breeze,Vision Strikers,13,FULL SENSE,5,44:30,1,0,Vision Strikers,13,FULL SENSE,5,1,2021
2,Valorant Champions 2021,Group Stage,Opening (C),Team Vikings vs Crazy Raccoon,Icebox,Team Vikings,13,Crazy Raccoon,9,59:48,1,0,Team Vikings,13,Crazy Raccoon,9,1,2021
3,Valorant Champions 2021,Group Stage,Opening (C),Team Vikings vs Crazy Raccoon,Haven,Team Vikings,13,Crazy Raccoon,8,52:48,1,0,Team Vikings,13,Crazy Raccoon,8,1,2021
4,Valorant Champions 2021,Group Stage,Opening (D),FNATIC vs Cloud9,Icebox,FNATIC,13,Cloud9,11,59:50,1,0,FNATIC,13,Cloud9,11,1,2021


In [4]:
all_matches.to_csv(f"all_matches_{DATA_VERSION}.csv", index=False)


In [5]:
# View all different files
df1 = pd.read_csv("./vct_2021/players_stats/players_stats.csv") # Player stats: ACS, KDA, FK, FD, headshot %
df3 = pd.read_csv("./vct_2021/matches/draft_phase.csv") # Map picks/bans
df5 = pd.read_csv("./vct_2021/matches/eco_rounds.csv") # Eco rounds
df10 = pd.read_csv("./vct_2021/matches/eco_stats.csv") # Pistol rounds
df7 = pd.read_csv("./vct_2021/matches/maps_scores.csv") # Opponent map matchup & map win rate
df9 = pd.read_csv("./vct_2021/matches/team_mapping.csv") # Logistics; PRX = Paper Rex

# Debatable
df2 = pd.read_csv("./vct_2021/matches/win_loss_methods_count.csv") # Plant/defuse success & closing patterns
df4 = pd.read_csv("./vct_2021/matches/draft_phase.csv") # Perma bans
df6 = pd.read_csv("./vct_2021/players_stats/players_stats.csv") # Clutch factor; none for per game/team. And role adjusted stats
# Roster stability score need to be calculated manually because tables do not provide join/leave dates

# IMPORTS
import matplotlib.pyplot as plt
import pandas as pd
import os

## Step 1: Exploratory Data Analysis (EDA)
Here we must clean data and define what is ACTUALLY useful rather than what we think is useful. This step is made of many points. At the top here, I will keep track of which stats seem to pass the study and move on to be used in the model.  
See this video for univariate and bivariate [here](https://www.youtube.com/watch?v=JG8GRlMjp3c)

**Charts moved out:** all the matplotlib scatter plots / heatmaps / bar charts for this EDA section live in the companion notebook `a+aron_plots.ipynb`

### 1.1 Data Cleanup
Make a list of tier 1 teams so you can remove all the irrelavant data before any calculates. **Any blank values (nulls) should also be removed to prevent skewed results.** Duplicates should also be watched out for. China stats are very missing so those need to be cared for so that it doesn't screw the data over. Same with player changes, we want the latest roster.

**Current:** the "duplicates" concern flagged above was real and larger than expected, fix is below. Tier-1-team filtering and the China-data nad roster-change concerns mentioned above are still open -- not addressed by this fix.


In [ ]:
# Player stats
# root_path, DATA_YEARS, DATA_VERSION come from the shared config cell above

drop_cols = [
    'Rounds Played',
    'Stage',
    'Match Type',
    'Rating',
    'Kill, Assist, Trade, Survive %',
    'Average Damage Per Round',
    'Kills Per Round',
    'Assists Per Round',
    'First Kills Per Round',
    'First Assists Per Round',
    'Maximum Kills in a Single Map',
    'Kills',
    'Assists',
    'Deaths'
]

all_players = []
for year in DATA_YEARS:
    file_path = os.path.join(root_path, f"vct_{year}/players_stats/players_stats.csv")
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)

        # Prefer the tournament-wide rollup rows...
        allstage = df[(df['Stage'] == 'All Stages') & (df['Match Type'] == 'All Match Types')]
        # ...falling back to whatever a player DOES have if they're missing that rollup entirely
        covered = set(zip(allstage['Tournament'], allstage['Teams'], allstage['Player']))
        key_tuples = list(zip(df['Tournament'], df['Teams'], df['Player']))
        fallback = df[[k not in covered for k in key_tuples]]
        df = pd.concat([allstage, fallback])

        # Within whatever's left, keep only the single row combining ALL agents a player used
        # (the row with the most Rounds Played -- the per-single-agent rows are subsets of it).
        df = df.sort_values('Rounds Played').drop_duplicates(
            subset=['Tournament', 'Teams', 'Player'], keep='last'
        )

        # Compute kda and fk_diff
        df['kda'] = (df['Kills'] + df['Assists']) / df['Deaths'].replace(0, 1)  # avoid division by 0
        df['fk_diff'] = df['First Kills'] - df['First Deaths']

        # Drop unnecessary columns
        df = df.drop(columns=drop_cols, errors='ignore')

        # Add year column
        df['Year'] = year

        all_players.append(df)
    else:
        print(f"File not found: {file_path}")

# Combine all years
player_stats_all = pd.concat(all_players, ignore_index=True)

# Safety net: if this cell is ever re-run without restarting the kernel (a common Jupyter mistake),
# don't let leftover appended rows from a previous run silently double the data.
player_stats_all = player_stats_all.drop_duplicates(subset=['Tournament', 'Teams', 'Player', 'Year'])

# Save to CSV at root (filename tracks whatever years were actually detected)
player_stats_all.to_csv(f"player_stats_{DATA_VERSION}.csv", index=False)

print(f"Combined player stats saved as 'player_stats_{DATA_VERSION}.csv' -- {len(player_stats_all)} rows "
      f"(one row per player per tournament, after removing per-stage/per-agent breakdown rows)")


Combined player stats saved as 'player_stats_2021_2025.csv' -- 42605 rows (one row per player per tournament, after removing per-stage/per-agent breakdown rows)


In [7]:
# Eco
all_eco = []


for year in DATA_YEARS:
    file_path = os.path.join(root_path, f"vct_{year}/matches/eco_rounds.csv")
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)

        # Drop rows with missing Loadout Value or Outcome
        df = df.dropna(subset=['Loadout Value', 'Outcome'])
        df['Loadout Value'] = (
            df['Loadout Value']
            .astype(str)                        # ensure it's string
            .str.replace('k', '', regex=False)   # remove 'k'
            .astype(float) * 1000                # convert to integer
        )

        # Filter only Eco rounds
        eco = df[df['Type'].str.contains('Eco', na=False)].copy()
        # Compute round_win column
        eco['round_win'] = (eco['Outcome'] == 'Win').astype(int)

        # Add year column
        eco['Year'] = year

        all_eco.append(eco)
    else:
        print(f"File not found: {file_path}")

# Combine all years
eco_all = pd.concat(all_eco, ignore_index=True)

# Save to CSV at root
eco_all.to_csv(f"eco_rounds_{DATA_VERSION}.csv", index=False)

print(f"Combined eco rounds saved as 'eco_rounds_{DATA_VERSION}.csv'")


Combined eco rounds saved as 'eco_rounds_2021_2025.csv'


In [8]:
# ==========PISTOL ROUNDS (ALL YEARS)==========
all_pistol = []

for year in DATA_YEARS:
    file_path = os.path.join(root_path, f"vct_{year}/matches/eco_stats.csv")
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)

        # Remove aggregated rows like "All Maps" if needed
        df = df[df['Map'] != 'All Maps'].copy()

        # Keep only pistol rounds
        df = df[df['Type'] == 'Pistol Won'].copy()

        # Drop only rows missing essential info
        df = df.dropna(subset=['Team', 'Map', 'Won'])

        # Ensure Won is numeric
        df['Won'] = pd.to_numeric(df['Won'], errors='coerce').fillna(0)

        # Add Year column
        df['Year'] = year

        all_pistol.append(df)
    else:
        print(f"File not found: {file_path}")

# Combine all years
pistol_all = pd.concat(all_pistol, ignore_index=True)
pistol = pistol_all.copy()

# Save to CSV
pistol_all.to_csv(f"pistol_rounds_{DATA_VERSION}.csv", index=False)

print(f"Combined pistol rounds saved as 'pistol_rounds_{DATA_VERSION}.csv', total rows: {len(pistol_all)}")


Combined pistol rounds saved as 'pistol_rounds_2021_2025.csv', total rows: 40866


In [9]:
# Picks Bans
all_pickban = []

for year in DATA_YEARS:
    file_path = os.path.join(root_path, f"vct_{year}/matches/draft_phase.csv")
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)

        # Drop rows with missing Team, Action, or Map
        df = df.dropna(subset=['Team', 'Action', 'Map'])

        # Reset index
        df = df.reset_index(drop=True)

        # Strip whitespace and lowercase
        df['Action'] = df['Action'].str.strip().str.lower()
        df['Team'] = df['Team'].str.strip()
        df['Map'] = df['Map'].str.strip()

        # Add year column
        df['Year'] = year

        all_pickban.append(df)
    else:
        print(f"File not found: {file_path}")

# Combine all years
pickban_all = pd.concat(all_pickban, ignore_index=True)

# Save to CSV at root
pickban_all.to_csv(f"pickban_{DATA_VERSION}.csv", index=False)

print(f"Combined pick/ban data saved as 'pickban_{DATA_VERSION}.csv'")


Combined pick/ban data saved as 'pickban_2021_2025.csv'


### 1.2 Univariate EDA
Univariate is used to determine the first pass of some of these values. Here we ask, "Does this feature matter at all?" and "Is it anyhow related to winning?". This is the important first step as you can see ever so slightly the possible relationship between win and factor.

**Univariate Analysis Approach:**
- **Correct methodology**: We aggregate features to team level (per tournament) and compare against team win rates
- **Plots**: Scatter plots show the relationship between feature values and win rates
- **Bins**: Quartile binning helps identify non-linear relationships and shows clear patterns
- **Both methods are complementary**: Plots show distribution, bins show discrete patterns

**Results Summary (2021-2025):**  
**FK-FD (fk_diff)** - Passes univariate EDA, plots roughly show some correlation  
**Headshot %** - Failed univariate EDA as increase of headshot % did not anyhow increase the win rate of the team, this value will not be studied or used  
**ACS, KDA** - Passes univariate EDA but is very similar hence we can pick one, drop the other  
**Eco Rounds** - Passes univariate EDA, specifically round win rate and avg loadout but we have to remember it seems like how they manage money is more important seeing that loadout is the source of pattern  
**Pistol Rounds** - Passes univariate EDA and we can see if you win both pistols, the win rate skyrockets as compared to not winning any pistols  
**Map win rate** - Passes univariate EDA  
**Opponent map matchup** - Sample size small so there isn't a lot to see but seems ok correlation  
**Map picks/bans** - Poor major predictor but can be used with other factors  

In [10]:
# ==========PLAYER STATS (2021-2025)==========
# Univariate EDA: Check if player stats correlate with team win rates
# Using all years (2021-2025) for comprehensive analysis

# Make sure 'Headshot %' is numeric (convert percentage string to float)
player_stats_all['Headshot %'] = player_stats_all['Headshot %'].str.rstrip('%').astype(float)

# Metrics to study: KDA, Headshot %, and ACS
metrics = ['kda', 'Headshot %', 'Average Combat Score']

# --- Aggregate player metrics to team level (all years) ---
# Group by Tournament and Teams to get average stats per team per tournament
team_stats = player_stats_all.groupby(
    ['Tournament', 'Teams'],
    as_index=False
).agg({
    'kda': 'mean',
    'Headshot %': 'mean',
    'Average Combat Score': 'mean'
})

# --- Compute team win rates using ALL matches (2021-2025) ---
# Changed from matches[0] to all_matches to include all years
team_wins = all_matches.groupby(
    ['Tournament', 'team'],
    as_index=False
)['win'].mean()

# Rename for consistent merge (standardize column name)
team_wins.rename(columns={'team': 'Teams'}, inplace=True)

# --- Merge metrics with win rate ---
team_metrics = team_stats.merge(
    team_wins,
    on=['Tournament', 'Teams'],
    how='inner'
)

# --- BINS: Bin analysis for each metric ---
print("\n=== BIN ANALYSIS: Player Stats ===")
for m in metrics:
    # Create 4 quartile bins
    team_metrics[f'{m}_bin'] = pd.qcut(team_metrics[m], 4, duplicates='drop')
    # Compute average win rate per bin
    bin_summary = team_metrics.groupby(f'{m}_bin', observed=True).agg(
        avg_win_rate=('win', 'mean'),
        count=('win', 'count')
    ).reset_index()
    print(f"\n{m} Bins -> Average Win Rate:")
    print(bin_summary)

# --- First Kill Differential Analysis ---
# Aggregate First Kills / First Deaths per player
player_fk = player_stats_all.groupby(
    ['Tournament', 'Teams', 'Player'],
    as_index=False
).agg({
    'First Kills': 'sum',
    'First Deaths': 'sum'
})

# Calculate FK differential (First Kills - First Deaths)
player_fk['fk_diff'] = player_fk['First Kills'] - player_fk['First Deaths']

# Aggregate to team level (sum of all players' FK differentials)
team_fk = player_fk.groupby(
    ['Tournament', 'Teams'],
    as_index=False
)['fk_diff'].sum()

# Merge with win rates
team_fk_merged = team_fk.merge(
    team_wins,
    on=['Tournament', 'Teams'],
    how='inner'
)

# --- BINS: FK diff bin analysis ---
team_fk_merged['fk_diff_bin'] = pd.qcut(team_fk_merged['fk_diff'], 4, duplicates='drop')
fk_bin_summary = team_fk_merged.groupby('fk_diff_bin', observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()
print("\n=== FK Differential Bins -> Average Win Rate ===")
print(fk_bin_summary)



=== BIN ANALYSIS: Player Stats ===

kda Bins -> Average Win Rate:
          kda_bin  avg_win_rate  count
0   (0.163, 1.05]      0.023659   2053
1   (1.05, 1.289]      0.251585   2053
2  (1.289, 1.462]      0.470868   2052
3  (1.462, 2.854]      0.648206   2053

Headshot % Bins -> Average Win Rate:
  Headshot %_bin  avg_win_rate  count
0  (7.749, 20.8]      0.271434   2094
1   (20.8, 23.2]      0.366514   2121
2   (23.2, 25.6]      0.384316   1991
3   (25.6, 41.0]      0.373244   1937

Average Combat Score Bins -> Average Win Rate:
  Average Combat Score_bin  avg_win_rate  count
0          (62.999, 181.2]      0.048386   2058
1           (181.2, 197.8]      0.272050   2062
2           (197.8, 209.2]      0.454681   2043
3          (209.2, 254.75]      0.621694   2047



=== FK Differential Bins -> Average Win Rate ===
        fk_diff_bin  avg_win_rate  count
0  (-76.001, -10.0]      0.207423   2158
1     (-10.0, -3.0]      0.214020   1971
2       (-3.0, 7.0]      0.361774   2098
3      (7.0, 146.0]      0.621780   1984


In [11]:
# ==========ECO ROUNDS (2021-2025)==========
# Univariate EDA: Analyze eco round performance (loadout value and round win rate)
# Using all years (2021-2025) - changed from eco to eco_all

# Aggregation columns for grouping
agg_cols = ['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team']

# Aggregate eco rounds per team per match (using eco_all for all years)
eco_team = eco_all.groupby(agg_cols).agg(
    avg_loadout=('Loadout Value', 'mean'),
    round_wins=('round_win', 'sum'),      # sum of wins
    total_rounds=('round_win', 'count')
).reset_index()

# Calculate round win rate (wins / total rounds)
eco_team['round_win_rate'] = eco_team['round_wins'] / eco_team['total_rounds']
# Proxy for match win: if team wins >50% of eco rounds, they likely won the match
eco_team['match_win_proxy'] = (eco_team['round_win_rate'] > 0.5).astype(int)

# --- BINS: Loadout value analysis ---
# Bin avg_loadout into 4 quartiles
eco_team['loadout_bin'] = pd.qcut(eco_team['avg_loadout'], 4, duplicates='drop')

# Compute average round win rate per bin
loadout_bin_summary = eco_team.groupby('loadout_bin', observed=True).agg(
    avg_round_win_rate=('round_win_rate', 'mean'),
    count=('round_win_rate', 'count')
).reset_index()

print("=== ECO ROUNDS: Loadout Value Bins -> Average Round Win Rate (2021-2025) ===")
print(loadout_bin_summary)

# --- BINS: Round win rate analysis ---
# Bin round win rate into quartiles
eco_team['round_bin'] = pd.qcut(eco_team['round_win_rate'], 4, duplicates='drop')

# Compute match win proxy rate per round win rate bin
round_bin_summary = eco_team.groupby('round_bin', observed=True).agg(
    match_win_rate=('match_win_proxy', 'mean'),
    count=('match_win_proxy', 'count')
).reset_index()

print("\n=== ECO ROUNDS: Round Win Rate Bins -> Match Win Proxy Rate (2021-2025) ===")
print(round_bin_summary)


=== ECO ROUNDS: Loadout Value Bins -> Average Round Win Rate (2021-2025) ===
        loadout_bin  avg_round_win_rate  count
0  (-0.001, 3100.0]            0.218497  10038
1  (3100.0, 3450.0]            0.347011  10033
2  (3450.0, 3750.0]            0.559989  10864
3  (3750.0, 4600.0]            0.623059   8967

=== ECO ROUNDS: Round Win Rate Bins -> Match Win Proxy Rate (2021-2025) ===
        round_bin  match_win_rate  count
0  (-0.001, 0.25]        0.000000  11903
1   (0.25, 0.333]        0.000000  13738
2  (0.333, 0.667]        0.528255   5238
3    (0.667, 1.0]        1.000000   9023


In [12]:
# ==========PISTOL ROUNDS (2021-2025)==========
# Univariate EDA: Analyze pistol round wins and their impact on map wins
# Using all years (2021-2025) - changed from matches[0] to all_matches and pistol to pistol_all

# Aggregation columns for grouping
agg_cols = ['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team']

# Aggregate per team per match (using pistol_all for all years)
pistol_team_map = pistol_all.groupby(agg_cols).agg(
    pistol_wins=('Won', 'sum'),
).reset_index()

# Cap pistol wins at 2 per map per match (max 2 pistol rounds per map)
pistol_team_map['pistol_wins'] = pistol_team_map['pistol_wins'].clip(upper=2)

# Compute win rate (0, 0.5, 1, depending on 0/1/2 wins)
pistol_team_map['pistol_win_rate'] = pistol_team_map['pistol_wins'] / 2

# Rename team column to match matches table (standardize naming)
pistol_team_map = pistol_team_map.rename(columns={'Team': 'team'})

# Merge with ALL matches table (map-level) - changed from matches[0] to all_matches
pistol_merged = all_matches.merge(
    pistol_team_map,
    on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
    how='left'
)

# Fill missing values (teams with no pistol data get 0 wins)
pistol_merged[['pistol_wins', 'pistol_win_rate']] = pistol_merged[['pistol_wins', 'pistol_win_rate']].fillna(0)

# Bin for analysis (0, 1, 2 pistol wins)
pistol_merged['pistol_wins_bin'] = pistol_merged['pistol_wins'].astype(int)

# --- BINS: Compute map win rate per pistol bin ---
pistol_bin_summary = pistol_merged.groupby('pistol_wins_bin', observed=True).agg(
    map_win_rate=('win', 'mean'),
    num_maps=('win', 'count')
).reset_index().sort_values('pistol_wins_bin')

print("=== PISTOL ROUNDS: Pistol Wins Bins -> Map Win Rate (2021-2025) ===")
print(pistol_bin_summary)


=== PISTOL ROUNDS: Pistol Wins Bins -> Map Win Rate (2021-2025) ===
   pistol_wins_bin  map_win_rate  num_maps
0                0      0.374804     23012
1                1      0.499974     19475
2                2      0.764030     10709


In [13]:
# ==========MAP WIN RATE (2021-2025)==========
# Univariate EDA: Analyze historical map win rate as a predictor
# Using all years (2021-2025) - changed from matches[1] to all_matches

# Compute historical win rate per Team x Map (using all matches)
# This calculates each team's win rate on each map across all tournaments
team_map_winrate = all_matches.groupby(['team', 'Map'], observed=True).agg(
    historical_win_rate=('win', 'mean'),
    num_matches=('win', 'count')
).reset_index()

# Merge historical win rate back to each match
matches_hist = all_matches.merge(
    team_map_winrate,
    on=['team', 'Map'],
    how='left'
)

# Compute correlation between historical win rate and actual match outcomes
corr = matches_hist['win'].corr(matches_hist['historical_win_rate'])
print(f"=== MAP WIN RATE: Correlation (2021-2025) ===")
print(f"Correlation between historical map win rate and actual wins: {corr:.3f}")

# --- BINS: Bin historical win rate and check actual win rate ---
# Create bins for historical win rate
matches_hist['hist_winrate_bin'] = pd.qcut(matches_hist['historical_win_rate'], 4, duplicates='drop')

# Compute actual win rate per bin
winrate_bin_summary = matches_hist.groupby('hist_winrate_bin', observed=True).agg(
    actual_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("\n=== MAP WIN RATE: Historical Win Rate Bins -> Actual Win Rate (2021-2025) ===")
print(winrate_bin_summary)


=== MAP WIN RATE: Correlation (2021-2025) ===
Correlation between historical map win rate and actual wins: 0.534

=== MAP WIN RATE: Historical Win Rate Bins -> Actual Win Rate (2021-2025) ===
  hist_winrate_bin  actual_win_rate  count
0  (-0.001, 0.375]         0.119844  13551
1   (0.375, 0.545]         0.482777  13064
2   (0.545, 0.667]         0.614635  14267
3     (0.667, 1.0]         0.804447  12232


In [14]:
# ==========OPPONENT MAP MATCHUP (2021-2025)==========
# Univariate EDA: Analyze head-to-head matchup win rates
# Using all years (2021-2025) - changed from matches[0] to all_matches

# NOTE: this is a self-referential (leaky) univariate check -- each match's own outcome
# is part of the "historical" matchup win rate it's compared against, which inflates the
# correlation below. The actual model in Step 3.3/3.5 uses a leakage-safe, shrunk version
# instead (build_map_matchup_stats), so this cell is EDA-only, not what feeds the model.

# Compute historical matchup stats (team vs opponent on specific map)
matchup_stats_eda = all_matches.groupby(['team', 'opponent', 'Map'], observed=True).agg(
    matches_played=('win', 'count'),
    wins=('win', 'sum'),
    win_rate=('win', 'mean')
).reset_index()

# Show top matchups by win rate
print("=== OPPONENT MATCHUP: Top 10 Matchups by Win Rate (2021-2025) ===")
print(matchup_stats_eda.sort_values(['win_rate'], ascending=False).head(10))

# Merge historical matchup win rate back to each match
matchup_merged = all_matches.merge(
    matchup_stats_eda,
    on=['team', 'opponent', 'Map'],
    how='left',
    suffixes=('', '_hist')
)

# Compute correlation
corr_matchup = matchup_merged['win'].corr(matchup_merged['win_rate'])
print(f"\n=== OPPONENT MATCHUP: Correlation (2021-2025) ===")
print(f"Correlation team vs opponent map matchup: {corr_matchup:.3f}")

# --- BINS: Bin matchup win rate and check actual win rate ---
# Create bins for matchup win rate (only for matchups with sufficient data)
matchup_merged_filtered = matchup_merged[matchup_merged['matches_played'] >= 2].copy()
matchup_merged_filtered['matchup_bin'] = pd.qcut(matchup_merged_filtered['win_rate'], 4, duplicates='drop')

# Compute actual win rate per bin
matchup_bin_summary = matchup_merged_filtered.groupby('matchup_bin', observed=True).agg(
    actual_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("\n=== OPPONENT MATCHUP: Matchup Win Rate Bins -> Actual Win Rate (2021-2025) ===")
print(matchup_bin_summary)


=== OPPONENT MATCHUP: Top 10 Matchups by Win Rate (2021-2025) ===
                    team        opponent     Map  matches_played  wins  \
26                 0Zero           Todak  Icebox               1     1   
46195                色狗幫     UnityBelief    Bind               1     1   
0      #1 Victory Royale        Karasuno    Bind               1     1   
1      #1 Victory Royale        Karasuno   Haven               1     1   
23                 0Zero         Inertia  Icebox               1     1   
21                 0Zero          AlphaQ   Haven               1     1   
4              #FIXBUCKY        NA TRAPE  Ascent               1     1   
20                 0Zero          AlphaQ  Ascent               1     1   
35           100 Thieves           Akrew  Breeze               1     1   
7        #PROPLAYERGAGAL  Galaxy Rangers  Ascent               1     1   

       win_rate  
26          1.0  
46195       1.0  
0           1.0  
1           1.0  
23          1.0  
21         


=== OPPONENT MATCHUP: Correlation (2021-2025) ===
Correlation team vs opponent map matchup: 0.939

=== OPPONENT MATCHUP: Matchup Win Rate Bins -> Actual Win Rate (2021-2025) ===
       matchup_bin  actual_win_rate  count
0  (-0.001, 0.286]         0.041142   2941
1     (0.286, 0.5]         0.460538   4612
2     (0.5, 0.714]         0.658048   1199
3     (0.714, 1.0]         0.961751   2902


In [15]:
# ==========MAP PICKS AND BANS (2021-2025)==========
# Univariate EDA: Analyze map pick/ban preferences and their relationship to win rates
# Using all years (2021-2025) - changed from matches[0] to all_matches

# Count picks and bans per team per map
pickban_counts = (
    pickban_all
    .groupby(['Team', 'Action', 'Map'], observed=True)
    .size()
    .reset_index(name='count')
)

# Compute team x map win rate (using all matches)
team_map_winrate = all_matches.groupby(['team', 'Map'], observed=True).agg(
    matches_played=('win', 'count'),
    wins=('win', 'sum'),
    win_rate=('win', 'mean')
).reset_index()

# Merge picks/bans with win rate
pickban_merged = pickban_counts.merge(
    team_map_winrate,
    left_on=['Team', 'Map'],
    right_on=['team', 'Map'],
    how='left'
)

# Compute fractions of total actions per team
# Total number of picks + bans per team
team_total_actions = pickban_merged.groupby('Team')['count'].sum().reset_index().rename(columns={'count': 'total_actions'})

pickban_merged = pickban_merged.merge(team_total_actions, on='Team', how='left')

# Fraction of actions per map (how often team picks/bans this map relative to all their actions)
pickban_merged['action_fraction'] = pickban_merged['count'] / pickban_merged['total_actions']

# Pivot picks and bans into separate columns
pick_fraction = pickban_merged[pickban_merged['Action'] == 'pick'][['Team', 'Map', 'action_fraction']].rename(columns={'action_fraction': 'pick_fraction'})
ban_fraction = pickban_merged[pickban_merged['Action'] == 'ban'][['Team', 'Map', 'action_fraction']].rename(columns={'action_fraction': 'ban_fraction'})

team_pref = pick_fraction.merge(ban_fraction, on=['Team', 'Map'], how='outer').fillna(0)

# Compute preference score (pick_fraction - ban_fraction)
# Positive = prefer to pick, Negative = prefer to ban
team_pref['pref_score'] = team_pref['pick_fraction'] - team_pref['ban_fraction']

# Merge actual win rate
team_pref = team_pref.merge(
    team_map_winrate[['team', 'Map', 'win_rate']],
    left_on=['Team', 'Map'],
    right_on=['team', 'Map'],
    how='left'
)

# Keep relevant columns
team_pref = team_pref[['Team', 'Map', 'pick_fraction', 'ban_fraction', 'pref_score', 'win_rate']].dropna()

print("=== MAP PICKS/BANS: Sample Data (2021-2025) ===")
print(team_pref.head(10))

# --- BINS: Bin preference score and check win rate ---
team_pref['pref_bin'] = pd.qcut(team_pref['pref_score'], 4, duplicates='drop')

pref_bin_summary = team_pref.groupby('pref_bin', observed=True).agg(
    avg_win_rate=('win_rate', 'mean'),
    count=('win_rate', 'count')
).reset_index()

print("\n=== MAP PICKS/BANS: Preference Score Bins -> Win Rate (2021-2025) ===")
print(pref_bin_summary)


=== MAP PICKS/BANS: Sample Data (2021-2025) ===
          Team       Map  pick_fraction  ban_fraction  pref_score  win_rate
0  100 Thieves     Abyss       0.003125      0.009375   -0.006250  0.000000
1  100 Thieves    Ascent       0.062500      0.071875   -0.009375  0.614035
2  100 Thieves      Bind       0.084375      0.081250    0.003125  0.541667
3  100 Thieves    Breeze       0.034375      0.037500   -0.003125  0.633333
4  100 Thieves   Corrode       0.000000      0.003125   -0.003125  1.000000
5  100 Thieves  Fracture       0.031250      0.018750    0.012500  0.590909
6  100 Thieves     Haven       0.065625      0.059375    0.006250  0.576271
7  100 Thieves    Icebox       0.059375      0.068750   -0.009375  0.625000
8  100 Thieves     Lotus       0.006250      0.100000   -0.093750  0.357143
9  100 Thieves     Pearl       0.003125      0.043750   -0.040625  0.444444

=== MAP PICKS/BANS: Preference Score Bins -> Win Rate (2021-2025) ===
            pref_bin  avg_win_rate  count
0  

### 1.3 Correlation Pruning EDA
We want to get rid of redundant factors. KDA and ACS are often used a lot but never together. They are somewhat related values and have shown to have a similar relationship with win rate. I don't see a need to have to calculate them together so ACS is pruned

In [16]:
# ==========KDA VS ACS CORRELATION (2021-2025)==========
# Correlation pruning: Remove redundant features that are highly correlated
# Using team_metrics from Player Stats section (updated variable name)

corr_matrix = team_metrics[['kda', 'Average Combat Score']].corr()
print("=== CORRELATION PRUNING: KDA vs ACS (2021-2025) ===")
print("Correlation matrix:\n", corr_matrix)

threshold = 0.8  # Threshold for high correlation
if abs(corr_matrix.loc['kda', 'Average Combat Score']) > threshold:
    print(f"\nKDA and ACS are highly correlated ({corr_matrix.loc['kda', 'Average Combat Score']:.2f}), pruning ACS")
    team_metrics = team_metrics.drop(columns=['Average Combat Score'])
    metrics = [m for m in metrics if m != 'Average Combat Score']  # update metrics list for plots
else:
    print(f"\nKDA and ACS correlation is moderate ({corr_matrix.loc['kda', 'Average Combat Score']:.2f}), keep both")


=== CORRELATION PRUNING: KDA vs ACS (2021-2025) ===
Correlation matrix:
                            kda  Average Combat Score
kda                   1.000000              0.924829
Average Combat Score  0.924829              1.000000

KDA and ACS are highly correlated (0.92), pruning ACS


### 1.4 Bivariate & Grouped EDA
Trying to see how two things interact together. This one is not the same as univariate (obviously). My take on this is to make certain values stronger than they were before especially factors that don't really show much relationship by themselves. We want to see if we can classify better than seeing one factor.  

In [17]:
# ==========BIVARIATE EDA: KDA VS FK DIFFERENTIAL (2021-2025)==========
# Bivariate analysis: How do KDA and FK differential interact to predict win rate?
# Using all years (2021-2025) - updated variable names

# Get KDA and win rate data
team_kda = team_metrics[['Tournament', 'Teams', 'kda', 'win']]
# Get FK differential data (from Player Stats section)
team_fk_data = team_fk_merged[['Tournament', 'Teams', 'fk_diff']]

# Merge KDA and FK data
team_kda_fk = team_kda.merge(
    team_fk_data,
    on=['Tournament', 'Teams'],
    how='inner'
)

# --- BINS: Create 2D bins and analyze win rates ---
# Create bins for both variables
team_kda_fk['kda_bin'] = pd.qcut(team_kda_fk['kda'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])
team_kda_fk['fk_bin'] = pd.qcut(team_kda_fk['fk_diff'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])

# Compute win rate for each combination
bivariate_summary = team_kda_fk.groupby(['kda_bin', 'fk_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== BIVARIATE: KDA x FK Diff Bins -> Win Rate (2021-2025) ===")
print(bivariate_summary.pivot(index='kda_bin', columns='fk_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_summary.pivot(index='kda_bin', columns='fk_bin', values='count'))


=== BIVARIATE: KDA x FK Diff Bins -> Win Rate (2021-2025) ===
fk_bin        Low       Med      High
kda_bin                              
Low      0.057402  0.051667  0.082995
Med      0.379627  0.332150  0.427088
High     0.558630  0.560190  0.643723

Sample sizes:
fk_bin    Low   Med  High
kda_bin                  
Low      1762   917    58
Med       969  1130   638
High      253   566  1918


In [18]:
# ==========BIVARIATE: PISTOL WINS X ECO ROUND WIN RATE (2021-2025)==========
# Combining early game (pistol) and economy management performance

# Merge pistol data with eco data
# First, aggregate eco data to match level
agg_cols = ['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team']
eco_match = eco_all.groupby(agg_cols).agg(
    eco_round_win_rate=('round_win', 'mean'),
    avg_loadout=('Loadout Value', 'mean')
).reset_index()
eco_match = eco_match.rename(columns={'Team': 'team'})

# Merge with pistol data (already has pistol_wins)
pistol_eco = pistol_merged.merge(
    eco_match,
    on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
    how='inner'
)

# --- BINS: 2D bin analysis ---
pistol_eco['pistol_bin'] = pd.cut(pistol_eco['pistol_wins'], bins=[-0.5, 0.5, 1.5, 2.5], labels=['0', '1', '2'])
pistol_eco['eco_bin'] = pd.qcut(pistol_eco['eco_round_win_rate'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])

bivariate_pistol_eco = pistol_eco.groupby(['pistol_bin', 'eco_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== BIVARIATE: Pistol Wins x Eco Win Rate Bins -> Win Rate (2021-2025) ===")
print(bivariate_pistol_eco.pivot(index='pistol_bin', columns='eco_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_pistol_eco.pivot(index='pistol_bin', columns='eco_bin', values='count'))


=== BIVARIATE: Pistol Wins x Eco Win Rate Bins -> Win Rate (2021-2025) ===
eco_bin          Low       Med      High
pistol_bin                              
0           0.231203  0.656716  1.000000
1           0.467899  0.540721  0.772727
2           0.380952  0.367925  0.769849

Sample sizes:
eco_bin       Low   Med   High
pistol_bin                    
0           10108    67      3
1           14828  2247   1408
2              21   106  10076


In [19]:
# ==========BIVARIATE: HISTORICAL WIN RATE X PISTOL WINS (2021-2025)==========
# Combining team's historical performance with early game performance

# Merge historical win rate with pistol data
hist_pistol = matches_hist.merge(
    pistol_merged[['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team', 'pistol_wins']],
    on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
    how='inner'
)

# --- BINS: 2D bin analysis ---
hist_pistol['hist_bin'] = pd.qcut(hist_pistol['historical_win_rate'], 4, duplicates='drop', labels=['Q1', 'Q2', 'Q3', 'Q4'])
hist_pistol['pistol_bin'] = pd.cut(hist_pistol['pistol_wins'], bins=[-0.5, 0.5, 1.5, 2.5], labels=['0', '1', '2'])

bivariate_hist_pistol = hist_pistol.groupby(['hist_bin', 'pistol_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== BIVARIATE: Historical Win Rate x Pistol Wins Bins -> Win Rate (2021-2025) ===")
print(bivariate_hist_pistol.pivot(index='hist_bin', columns='pistol_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_hist_pistol.pivot(index='hist_bin', columns='pistol_bin', values='count'))


=== BIVARIATE: Historical Win Rate x Pistol Wins Bins -> Win Rate (2021-2025) ===
pistol_bin         0         1         2
hist_bin                                
Q1          0.072964  0.121624  0.329538
Q2          0.365936  0.472769  0.750564
Q3          0.508311  0.604573  0.822333
Q4          0.727420  0.791351  0.923634

Sample sizes:
pistol_bin     0     1     2
hist_bin                    
Q1          7305  4703  1581
Q2          5654  4774  2658
Q3          5715  5379  3197
Q4          4318  4625  3313


In [20]:
# ==========BIVARIATE: KDA X ECO ROUND WIN RATE (2021-2025)==========
# Combining combat performance with economy management

# Merge team KDA with eco data at match level
# First, get team KDA per tournament (from earlier analysis)
team_kda_data = team_metrics[['Tournament', 'Teams', 'kda']].rename(columns={'Teams': 'team'})

# Merge with eco match data
eco_kda = eco_match.merge(
    team_kda_data,
    on=['Tournament', 'team'],
    how='inner'
)

# Merge with match results to get win outcome
eco_kda = eco_kda.merge(
    all_matches[['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team', 'win']],
    on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
    how='inner'
)

# --- BINS: 2D bin analysis ---
eco_kda['kda_bin'] = pd.qcut(eco_kda['kda'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])
eco_kda['eco_bin'] = pd.qcut(eco_kda['eco_round_win_rate'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])

bivariate_kda_eco = eco_kda.groupby(['kda_bin', 'eco_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== BIVARIATE: KDA x Eco Win Rate Bins -> Win Rate (2021-2025) ===")
print(bivariate_kda_eco.pivot(index='kda_bin', columns='eco_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_kda_eco.pivot(index='kda_bin', columns='eco_bin', values='count'))


=== BIVARIATE: KDA x Eco Win Rate Bins -> Win Rate (2021-2025) ===
eco_bin       Low       Med      High
kda_bin                              
Low      0.203636  0.277411  0.561590
Med      0.430627  0.588542  0.778992
High     0.536949  0.712206  0.872275

Sample sizes:
eco_bin   Low  Med  High
kda_bin                 
Low      9625  757  2541
Med      8130  768  4027
High     7118  893  4909


In [21]:
# ==========GROUPED EDA: MAP X PISTOL WINS (2021-2025)==========
# Grouped analysis: How does pistol performance vary by map?

# Use pistol_merged which already has map and pistol wins
map_pistol = pistol_merged.groupby(['Map', 'pistol_wins_bin'], observed=True).agg(
    map_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== GROUPED: Map x Pistol Wins -> Win Rate (2021-2025) ===")
print("\nSample sizes:")
pivot_count = map_pistol.pivot(index='Map', columns='pistol_wins_bin', values='count')
print(pivot_count)


=== GROUPED: Map x Pistol Wins -> Win Rate (2021-2025) ===

Sample sizes:
pistol_wins_bin     0     1     2
Map                              
Abyss              67    58    37
Ascent           5733  4063  2398
Bind             4536  3146  1776
Breeze            853  1506   793
Corrode            53    66    27
Fracture          468   706   398
Haven            4537  3614  1963
Icebox           2904  2938  1644
Lotus             436   486   222
Pearl             142   202    84
Split            2976  2476  1272
Sunset            225   214    95


In [22]:
# ==========GROUPED EDA: PISTOL WINS X FK DIFFERENTIAL (2021-2025)==========
# Combining early game performance (pistol) with first engagement performance (FK diff)
# This explores if teams that win pistols AND have good FK differential perform better

# Get FK diff data at match level - need to merge with match data
# First, get team FK diff per tournament (from earlier analysis)
team_fk_match = team_fk_merged[['Tournament', 'Teams', 'fk_diff']].rename(columns={'Teams': 'team'})

# Merge FK diff with pistol data at match level
# pistol_merged already has 'win' and 'Year' from all_matches, so we just need to add FK diff
pistol_fk = pistol_merged.merge(
    team_fk_match,
    on=['Tournament', 'team'],
    how='inner'
)

# Ensure 'win' column exists - if merge dropped it somehow, add it back
if 'win' not in pistol_fk.columns:
    pistol_fk = pistol_fk.merge(
        all_matches[['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team', 'win']],
        on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
        how='inner'
    )

# --- BINS: 2D bin analysis ---
pistol_fk['pistol_bin'] = pd.cut(pistol_fk['pistol_wins'], bins=[-0.5, 0.5, 1.5, 2.5], labels=['0', '1', '2'])
pistol_fk['fk_bin'] = pd.qcut(pistol_fk['fk_diff'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])

bivariate_pistol_fk = pistol_fk.groupby(['pistol_bin', 'fk_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== GROUPED: Pistol Wins x FK Differential Bins -> Win Rate (2021-2025) ===")
print(bivariate_pistol_fk.pivot(index='pistol_bin', columns='fk_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_pistol_fk.pivot(index='pistol_bin', columns='fk_bin', values='count'))

# Calculate improvement over univariate
print("\n=== ANALYSIS: Interaction Strength ===")
pistol_only = pistol_fk.groupby('pistol_bin', observed=True)['win'].mean()
fk_only = pistol_fk.groupby('fk_bin', observed=True)['win'].mean()
print(f"Pistol-only effect range: {pistol_only.max() - pistol_only.min():.3f}")
print(f"FK-only effect range: {fk_only.max() - fk_only.min():.3f}")
print(f"Combined effect range: {bivariate_pistol_fk['avg_win_rate'].max() - bivariate_pistol_fk['avg_win_rate'].min():.3f}")


=== GROUPED: Pistol Wins x FK Differential Bins -> Win Rate (2021-2025) ===
fk_bin           Low       Med      High
pistol_bin                              
0           0.231062  0.396565  0.555944
1           0.373357  0.492274  0.637675
2           0.633727  0.757224  0.854881

Sample sizes:
fk_bin       Low   Med  High
pistol_bin                  
0           8673  7860  6292
1           6771  6019  6657
2           2965  3184  4548

=== ANALYSIS: Interaction Strength ===
Pistol-only effect range: 0.387
FK-only effect range: 0.316
Combined effect range: 0.624


In [ ]:
# ==========GROUPED EDA: MAP PREFERENCE X HISTORICAL MAP WIN RATE (2021-2025)==========
# Strengthening map preference predictor by combining with historical performance
# Hypothesis: Teams that prefer maps they're historically good at should win more

# Get historical win rate at match level (from matches_hist)
# Merge team_pref with match data
pref_hist = all_matches.merge(
    team_pref[['Team', 'Map', 'pref_score', 'pick_fraction', 'ban_fraction']],
    left_on=['team', 'Map'],
    right_on=['Team', 'Map'],
    how='inner'
)

# Merge with historical win rate
pref_hist = pref_hist.merge(
    matches_hist[['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team', 'historical_win_rate']],
    on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
    how='inner'
)

# Create interaction features
# 1. Alignment: Does team prefer maps they're good at?
pref_hist['pref_hist_alignment'] = pref_hist['pref_score'] * pref_hist['historical_win_rate']
# 2. Strong preference + high win rate
pref_hist['strong_pref_high_win'] = ((pref_hist['pref_score'] > 0.1) & (pref_hist['historical_win_rate'] > 0.6)).astype(int)
# 3. Weak preference + low win rate (should avoid)
pref_hist['weak_pref_low_win'] = ((pref_hist['pref_score'] < -0.1) & (pref_hist['historical_win_rate'] < 0.4)).astype(int)

# --- BINS: Detailed analysis ---
pref_hist['pref_bin'] = pd.qcut(pref_hist['pref_score'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])
pref_hist['hist_bin'] = pd.qcut(pref_hist['historical_win_rate'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])

bivariate_pref_hist = pref_hist.groupby(['pref_bin', 'hist_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== GROUPED: Map Preference x Historical Win Rate Bins -> Win Rate (2021-2025) ===")
print(bivariate_pref_hist.pivot(index='pref_bin', columns='hist_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_pref_hist.pivot(index='pref_bin', columns='hist_bin', values='count'))

# Calculate improvement metrics
print("\n=== ANALYSIS: Map Preference Strengthening ===")
pref_only = pref_hist.groupby('pref_bin', observed=True)['win'].mean()
hist_only = pref_hist.groupby('hist_bin', observed=True)['win'].mean()
print(f"Preference-only effect range: {pref_only.max() - pref_only.min():.3f}")
print(f"Historical-only effect range: {hist_only.max() - hist_only.min():.3f}")
print(f"Combined effect range: {bivariate_pref_hist['avg_win_rate'].max() - bivariate_pref_hist['avg_win_rate'].min():.3f}")

# Alignment analysis
print(f"\nAlignment Score Correlation with Win: {pref_hist['pref_hist_alignment'].corr(pref_hist['win']):.3f}")
print(f"Strong Pref + High Win Rate Win Rate: {pref_hist[pref_hist['strong_pref_high_win']==1]['win'].mean():.3f}")
print(f"Other cases Win Rate: {pref_hist[pref_hist['strong_pref_high_win']==0]['win'].mean():.3f}")


=== GROUPED: Map Preference x Historical Win Rate Bins -> Win Rate (2021-2025) ===
hist_bin       Low       Med      High
pref_bin                              
Low       0.376737  0.583905  0.738180
Med       0.422446  0.593196  0.724744
High      0.417778  0.597814  0.740042

Sample sizes:
hist_bin   Low   Med  High
pref_bin                  
Low       4247  2771  1967
Med       2379  3498  3128
High      2475  2653  3816

=== ANALYSIS: Map Preference Strengthening ===
Preference-only effect range: 0.089
Historical-only effect range: 0.334
Combined effect range: 0.363

Alignment Score Correlation with Win: 0.052
Strong Pref + High Win Rate Win Rate: 0.721
Other cases Win Rate: 0.551


In [ ]:
# ==========GROUPED EDA: ECO ROUND PERFORMANCE X KDA (2021-2025)==========
# Combining economy management with combat performance
# This explores if teams that manage economy well AND have high KDA perform better

team_kda_data = team_metrics[['Tournament', 'Teams', 'kda']].rename(columns={'Teams': 'team'})

# Merge with eco match data
eco_kda_enhanced = eco_match.merge(
    team_kda_data,
    on=['Tournament', 'team'],
    how='inner'
)

# Merge with match results to get win outcome
eco_kda_enhanced = eco_kda_enhanced.merge(
    all_matches[['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team', 'win']],
    on=['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team'],
    how='inner'
)

# Create interaction features
# 1. Combined score: high KDA + high eco win rate
eco_kda_enhanced['kda_eco_score'] = (eco_kda_enhanced['kda'] / eco_kda_enhanced['kda'].max()) + \
                                     (eco_kda_enhanced['eco_round_win_rate'] / eco_kda_enhanced['eco_round_win_rate'].max())
# 2. Strong in both
eco_kda_enhanced['strong_both'] = ((eco_kda_enhanced['kda'] > eco_kda_enhanced['kda'].quantile(0.75)) &
                                   (eco_kda_enhanced['eco_round_win_rate'] > eco_kda_enhanced['eco_round_win_rate'].quantile(0.75))).astype(int)
# 3. Weak in both
eco_kda_enhanced['weak_both'] = ((eco_kda_enhanced['kda'] < eco_kda_enhanced['kda'].quantile(0.25)) &
                                (eco_kda_enhanced['eco_round_win_rate'] < eco_kda_enhanced['eco_round_win_rate'].quantile(0.25))).astype(int)

# --- BINS: Detailed analysis ---
eco_kda_enhanced['kda_bin'] = pd.qcut(eco_kda_enhanced['kda'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])
eco_kda_enhanced['eco_bin'] = pd.qcut(eco_kda_enhanced['eco_round_win_rate'], 3, duplicates='drop', labels=['Low', 'Med', 'High'])

bivariate_eco_kda = eco_kda_enhanced.groupby(['kda_bin', 'eco_bin'], observed=True).agg(
    avg_win_rate=('win', 'mean'),
    count=('win', 'count')
).reset_index()

print("=== GROUPED: Eco Round Performance x KDA Bins -> Win Rate (2021-2025) ===")
print(bivariate_eco_kda.pivot(index='kda_bin', columns='eco_bin', values='avg_win_rate'))
print("\nSample sizes:")
print(bivariate_eco_kda.pivot(index='kda_bin', columns='eco_bin', values='count'))

# Calculate improvement metrics
print("\n=== ANALYSIS: Interaction Strength ===")
kda_only = eco_kda_enhanced.groupby('kda_bin', observed=True)['win'].mean()
eco_only = eco_kda_enhanced.groupby('eco_bin', observed=True)['win'].mean()
print(f"KDA-only effect range: {kda_only.max() - kda_only.min():.3f}")
print(f"Eco-only effect range: {eco_only.max() - eco_only.min():.3f}")
print(f"Combined effect range: {bivariate_eco_kda['avg_win_rate'].max() - bivariate_eco_kda['avg_win_rate'].min():.3f}")

# Combined score analysis
print(f"\nCombined Score Correlation with Win: {eco_kda_enhanced['kda_eco_score'].corr(eco_kda_enhanced['win']):.3f}")
print(f"Strong in Both Win Rate: {eco_kda_enhanced[eco_kda_enhanced['strong_both']==1]['win'].mean():.3f}")
print(f"Other cases Win Rate: {eco_kda_enhanced[eco_kda_enhanced['strong_both']==0]['win'].mean():.3f}")
print(f"Weak in Both Win Rate: {eco_kda_enhanced[eco_kda_enhanced['weak_both']==1]['win'].mean():.3f}")


=== GROUPED: Eco Round Performance x KDA Bins -> Win Rate (2021-2025) ===
eco_bin       Low       Med      High
kda_bin                              
Low      0.203636  0.277411  0.561590
Med      0.430627  0.588542  0.778992
High     0.536949  0.712206  0.872275

Sample sizes:
eco_bin   Low  Med  High
kda_bin                 
Low      9625  757  2541
Med      8130  768  4027
High     7118  893  4909

=== ANALYSIS: Interaction Strength ===
KDA-only effect range: 0.398
Eco-only effect range: 0.398
Combined effect range: 0.669

Combined Score Correlation with Win: 0.465
Strong in Both Win Rate: 0.905
Other cases Win Rate: 0.466
Weak in Both Win Rate: 0.079


## Step 2: Observe and Take Notes


**What was already mentioned above:**
- We can see that KDA and ACS are redundant/very similar and in practice as well. We know from understanding of the game that they come from the same values, kills (basically). From my observation, the KDA plot looks ever so slightly stronger in correlation so for now, I drop ACS
- Headshot % was really bad univariate so I decided that we don't need to see it anymore, it isn't really showing of anything. There was an idea that I could combine that headshot % value with something more meaningful like KDA to improve the factor but I don't think it is that worth it and may just devalue KDA instead
- Map picks and bans are not decisive so it needs to be paired with another feature
- Opponent map matchup is a strong predictor like if team A won against team B on map 1 >70% of the time, they are 90%+ likely to win BUT there is less data to create this relationship since teams play with multiple different teams and not always with the same few teams.
    - Consider how this might skew internationals to be harder to predict versus regionals (since regionals play each other more than cross regions)

**More notes:**
- KDA, pistol wins, and FK diffs are pretty good predictors behind opponent matchup being the best
- Lets put eco round and KDA on interactions after eco round has been aggregated. The bivariate shows that this helps a lot (poor KDA but high eco win only gives about 50% win rate while good KDA and high eco win gives 80% win rate)
- Historical map win rate is a pretty good predictor as well but is even more powerful with opponent matchup. Let's find a way to make them a strong predictor together especially since they are, at the core, basically the same.
- Higher loadout value in eco rounds gives higher round win rate which is pretty logically, don't really need more digging in that. Generally, being able to win those eco rounds is good to match winning
- If we want to use eco rounds, we needed to aggregate the stats. Since it is so round by round based and loadout value is related to how an eco round goes, we need to make it a map-level feature. Pistol rounds, for example, though also round based, is limited to two per map so it is already "map-level" rather than changes by round. Having to go eco is already usually a bad sign since you usually lose to have no money, so how that got there and what money you still have is important.

**Thoughts about interactions:**
1. Additive "Interactions" - Here this is straightforward stuff, KDA + pistol wins + FK diff ~ wins. Each item works alone and no interaction is needed
2. Synergistic Interactions - Both items matter but together, they show a deeper picture. This is what we call our eco round x KDA interaction where as the team is better in their KDA, the more the profit from winning their eco rounds.
3. Conditional Interactions - Certain variable only matters when a certain condition is met. This is our map preference. Map preference doesn't really matter unless a team is already good at that map. Preference reflects confidence *on top* of skill
4. Contextual "Interactions" - This depends on the opponent or environment, things like that. Like our opponent matchup is a very hard factor to work with because it isn't a performance trait, rather the trait of a situation.

### Conclusion
| Factor                             | Type / Role                      | Notes / Next Steps                                                                                                   |
| ---------------------------------- | -------------------------------- | -------------------------------------------------------------------------------------------------------------------- |
| **KDA**                            | Strong additive                  | Keep as predictor; consider standardization or log transform (for linear/logistic models)                            |
| **FK diff**                        | Strong additive                  | Keep as predictor; may need shifted log (to handle negative values)                                                  |
| **Eco round**                      | Weak alone w/ aggregating | Aggregate per map/team; can include raw or binned (0–1 fraction). Consider including additive effect too if desired. |
| **Eco × KDA**                      | Interaction / synergy            | Captures that high KDA teams benefit more from eco wins; add as separate column.                                     |
| **Pistol round**                   | Strong additive                  | Keep as is; integer 0–2 no transformation needed.                                                   |
| **Historical map win rate (HMWR)** | Additive baseline                | Scale 0–1 or logit if using linear/logistic models; also used in conditional interaction with map preference.        |
| **Opponent map matchup (OMM)**     | Contextual / sparse              | Smooth/shrink (e.g., Bayesian prior) to stabilize; can also consider logit transform if linear/logistic.             |
| **Map preference × HMWR**          | Conditional interaction          | Captures “picking maps you are already strong at”; map preference alone is weak, only keep as interaction.           |


## Step 3: Pre-Model Data Modifications
Now we have to focus on aggregating, transforming, interactions, and shrinking/smoothing features. Be careful not to use the data that has already been altered and used for EDA, those are not the data we want to build off of.

### 3.1 Aggregating
At this point, I think we're only aggregating the eco rounds so that it can be compared on a map level rather than round by round. This is looked at through the average round win rate and average loadout value. I know, it flattens the relationship between loadout value and round win but loadout value is only most relevant when predicting the round win. Right now our aim is map level, map win.

Added: apparently I need to aggregate KDA too because technically we are looking at team level, map games. We aren't really looking at it player to player, but team to team wins.

In [25]:
# ==========AGGREGATING ECO ROUNDS==========
eco = pd.read_csv(f"eco_rounds_{DATA_VERSION}.csv")

# Drop any missing critical data
eco = eco.dropna(subset=['round_win','Loadout Value','Team','Map'])

# Make sure Loadout Value is numeric
eco['Loadout Value'] = pd.to_numeric(eco['Loadout Value'], errors='coerce')
eco = eco.dropna(subset=['Loadout Value'])

# Aggregate per team/map/match
agg_cols = ['Tournament','Stage','Match Type','Match Name','Map','Team','Year']

eco_agg = eco.groupby(agg_cols).agg(
    avg_eco_win_rate=('round_win','mean'),
    avg_loadout=('Loadout Value','mean'),
    eco_rounds_played=('round_win','count')
).reset_index()

# Preview the aggregated table
print(eco_agg.head(10))

# Optional: check overall statistics
print(eco_agg.describe())


                                          Tournament       Stage   Match Type  \
0  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
1  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
2  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
3  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
4  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
5  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
6  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
7  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Grand Final   
8  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Lower Final   
9  Champions Tour 2023: Americas Last Chance Qual...  Main Event  Lower Final   

                Match Name     Map         Team  Year  avg_eco_win_rate  \
0  KRÜ Esports vs LEVIATÁN  Ascen

In [26]:
team_kda = pd.read_csv(f"player_stats_{DATA_VERSION}.csv")

team_kda = player_stats_all.groupby(
    ['Tournament', 'Teams', 'Year'],
    as_index=False
).agg(
    team_kda=('kda', 'mean')
)

### 3.2 Basic Transformation
Let's transform aggregated KDA, FK diff, the aggregated eco rounds, and the HMWR.

Correction (bug fix, fixed in place): `team_fk` was originally read straight from the player-stats CSV with no groupby at all, so it was silently at player level instead of team level (unlike `team_kda` right below, which correctly grouped to team level). Fixed to match `team_kda`'s pattern.


In [27]:
# ==========TRANSFORM KDA==========
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

# Log transform
team_kda['kda_log'] = np.log1p(team_kda['team_kda'])

# Standardize
scaler = StandardScaler()
team_kda['kda_log_z'] = scaler.fit_transform(
    team_kda[['kda_log']]
)

# print(team_kda.head())

In [28]:
# ==========TRANSFORM FK DIFF==========
# BUG FIX (fixed in place, not logged as a new iteration -- genuine bug, not a design choice):
# this used to read player_stats straight off disk with NO groupby, so it was silently sitting at
# PLAYER level instead of TEAM level -- unlike team_kda right above, which correctly grouped by
# ['Tournament', 'Teams', 'Year']. Matching that same pattern here.
team_fk = player_stats_all.groupby(
    ['Tournament', 'Teams', 'Year'],
    as_index=False
).agg(
    fk_diff=('fk_diff', 'mean')
)

fk_min = team_fk['fk_diff'].min()
shift = abs(fk_min) + 1

team_fk['fk_shifted_log'] = np.log1p(team_fk['fk_diff'] + shift)

# Standardize
team_fk['fk_shifted_log_z'] = scaler.fit_transform(
    team_fk[['fk_shifted_log']]
)



In [29]:
# ==========TRANSFORM ECO==========
eps = 1e-6  # avoid division by zero or log(0)
eco_agg['eco_win_rate_logit'] = np.log(
    (eco_agg['avg_eco_win_rate'] + eps) / (1 - eco_agg['avg_eco_win_rate'] + eps)
)

# Standardize
scaler = StandardScaler()
eco_agg['eco_win_rate_z'] = scaler.fit_transform(
    eco_agg[['eco_win_rate_logit']]
)

eco_agg['eco_loadout_log'] = np.log1p(eco_agg['avg_loadout'])

eco_agg['eco_loadout_z'] = scaler.fit_transform(
    eco_agg[['eco_loadout_log']]
)

print(eco_agg[['avg_eco_win_rate','eco_win_rate_z','avg_loadout','eco_loadout_z']].head(10))
print(eco_agg[['eco_win_rate_z','eco_loadout_z']].describe())


   avg_eco_win_rate  eco_win_rate_z  avg_loadout  eco_loadout_z
0          0.333333       -0.040219  3766.666667       0.499199
1          0.500000        0.034195  3450.000000       0.118670
2          0.333333       -0.040219  3566.666667       0.262781
3          0.333333       -0.040219  3566.666667       0.262781
4          0.333333       -0.040219  3566.666667       0.262781
5          0.666667        0.108609  3566.666667       0.262781
6          0.666667        0.108609  3000.000000      -0.486932
7          0.333333       -0.040219  3133.333333      -0.298509
8          0.000000       -1.448996  4040.000000       0.802767
9          1.000000        1.517385  3750.000000       0.479983
       eco_win_rate_z  eco_loadout_z
count    3.990400e+04   3.990400e+04
mean    -8.368963e-17   9.059847e-16
std      1.000013e+00   1.000013e+00
min     -1.448996e+00  -3.519152e+01
25%     -8.374850e-02  -3.448527e-01
50%     -4.021915e-02   1.186701e-01
75%      1.086088e-01   4.799825e-01


### 3.3 Smoothing/Shrinkage
Here we need to perform some sort of toning-down on the OMM rate because that predictor, though strong, may be too strong! Think, if PRX has only ever played G2 once and lost, it will predict that they will lose the second time. Then maybe they do lose, the next prediction will stay with losing. We don't want the weight of this to be too strong or else it will sway the final prediction too much BUT it is still strong if there is a larger pool to look at. At the time of this bot's creation, PRX has won 9 maps and G2 has won 6 maps against each other. For a team like these two, a small pool of 1 or 2 matches would make it detrimental for a meaningful prediction. So we must downplay the value when the pool is small using Laplace/Bayesian smoothing.

TLDR; We smooth OMM by HMWR because OMM is more trustworthy when a team is actually good at the map. A win shouldn't be treated so highly if the pool against a certain team for a certain map is small. Go bigger picture!

In [30]:
def build_map_matchup_stats(matches_sub, beta=20, alpha=10):
    """
    Reusable version of the hierarchical HMWR -> OMM shrinkage pipeline below.
    Parameterized by whatever slice of match rows you pass in, so this logic lives in exactly ONE
    place -- called once here with the full history (for live use / Step 6), and again in Step 4/5
    with train-years-only data for leakage-safe backtesting, instead of being rebuilt from scratch
    under different names in each step (which is what happened the first time around).
    """
    raw_df = matches_sub.copy()

    # STEP 0: Global map win rate (lowest-level prior)
    global_map_wr = raw_df.groupby('Map', observed=True).agg(
        global_map_win_rate=('win', 'mean')
    ).reset_index()

    # STEP 1: Team historical map stats
    team_map_stats = raw_df.groupby(['team', 'Map'], observed=True).agg(
        team_map_wins=('win', 'sum'),
        team_map_matches=('win', 'count')
    ).reset_index()

    team_map_stats = team_map_stats.merge(
        global_map_wr,
        on='Map',
        how='left'
    )

    # STEP 2: Shrink team-map win rate toward global map WR
    team_map_stats['team_map_win_rate_shrunk'] = (
        team_map_stats['team_map_wins'] +
        beta * team_map_stats['global_map_win_rate']
    ) / (
        team_map_stats['team_map_matches'] + beta
    )

    # STEP 3: Raw opponent matchup stats
    matchup_stats = raw_df.groupby(['team', 'opponent', 'Map'], observed=True).agg(
        wins=('win', 'sum'),
        matches_played=('win', 'count')
    ).reset_index()

    # STEP 4: Merge SHRUNK team-map prior
    matchup_stats = matchup_stats.merge(
        team_map_stats[['team', 'Map', 'team_map_win_rate_shrunk']],
        on=['team', 'Map'],
        how='left'
    )

    matchup_stats['team_map_win_rate_shrunk'] = (
        matchup_stats['team_map_win_rate_shrunk'].fillna(0.5)
    )

    # STEP 5: Shrink opponent matchup toward team-map strength
    matchup_stats['opponent_matchup_smoothed'] = (
        matchup_stats['wins'] +
        alpha * matchup_stats['team_map_win_rate_shrunk']
    ) / (
        matchup_stats['matches_played'] + alpha
    )

    # STEP 6: Build FINAL modeling dataset (separate object)
    model_df = raw_df.merge(
        matchup_stats[
            ['team', 'opponent', 'Map',
             'opponent_matchup_smoothed',
             'matches_played']
        ],
        on=['team', 'opponent', 'Map'],
        how='left'
    )

    # STEP 7: Merge team-map prior too
    model_df = model_df.merge(
        team_map_stats[['team', 'Map', 'team_map_win_rate_shrunk']],
        on=['team', 'Map'],
        how='left'
    )

    # STEP 8: Final fallback
    model_df['opponent_matchup_smoothed'] = (
        model_df['opponent_matchup_smoothed']
        .fillna(model_df['team_map_win_rate_shrunk'])
        .fillna(0.5)
    )

    return team_map_stats, matchup_stats, model_df

# Live/all-history version -- used by the rest of this notebook (Step 4 draft simulator, Step 6 live predictions)
BETA = 20
ALPHA = 10
team_map_stats, matchup_stats, model_df = build_map_matchup_stats(all_matches, beta=BETA, alpha=ALPHA)

print("Hierarchical OMM smoothing complete.")


Hierarchical OMM smoothing complete.


### 3.4 Interactions
Here we have two interactions to make: Eco × KDA and Map preference × HMWR

In [31]:
# ==========ECO X KDA==========
# Merge KDA into eco_agg
eco_kda = eco_agg.merge(
    team_kda,
    left_on=['Tournament', 'Team', 'Year'],
    right_on=['Tournament', 'Teams', 'Year'],
    how='left'
)


# Create interaction by multiplying since it is not conditional
eco_kda['eco_x_kda'] = (
    eco_kda['eco_win_rate_z'] * eco_kda['kda_log_z']
)

eco_kda[['eco_win_rate_z', 'kda_log_z', 'eco_x_kda']].describe()
eco_kda[['eco_win_rate_z', 'kda_log_z', 'eco_x_kda']].corr()


,eco_win_rate_z,kda_log_z,eco_x_kda
eco_win_rate_z,1.000000,0.258539,0.465110
kda_log_z,0.258539,1.000000,-0.148599
eco_x_kda,0.465110,-0.148599,1.000000


In [32]:
# ==========MAP PREFERENCE X HMWR==========
pref_hist['pref_hist_alignment'] = (
    pref_hist['pref_score'] * pref_hist['historical_win_rate']
)

# print(pref_hist.head())

#### Notes:
- Aggregating was required on both eco rounds and KDA. I'm not sure if I'm missing something else but we want the level of the value to be used together. Like how it is easier to work with ft x ft rather than ft x m.
    - We are generally looking at map-team level. Some of the data is player by player but, unless we are building a multi-leveled model, we have to treat them as a team in order to cross with the match details.
    - Same with rounds which make up an entire match. The value of the data can't be drawn out according to context without leveling it to map level
- Basic transformation is performed because some value can be scale sensitive. Raw data is often just "data" and isn't very model friendly so transformations fix this. Especially looking at noise!
- Interactions multiplication is used to model how two factors combine, but the meaning depends on context. Eco × KDA is a synergistic interaction where both amplify each other, while Map Preference × HMWR is a conditional interaction where preference only matters if the team is already good on the map. Same math, different interpretation.

### 3.5 Team-Level-Across-History Rollups (for the win model)

The tables above (`team_kda`, `team_fk`, `eco_agg`, `pistol_team_map`) are all at *per-tournament* or
*per-match* granularity -- exactly what interactions like Eco x KDA needed. But the win model in Step 5
needs a single number per team ("how good is this team's KDA, overall, right now").

So this section rolls the tables above up one more level to a genuine team-level scalar.

In [33]:
# ==========SHRINKAGE CONSTANT FOR TEAM-MAP ECO/PISTOL FEATURES==========
# Same spirit as BETA/ALPHA in 3.3: a team's eco/pistol number ON ONE SPECIFIC MAP is shrunk toward
# their overall (all-map) average, weighted by how many team-map-match rows back it. A team with 40
# rows on Ascent gets a number close to its raw Ascent average; a team with 2 rows on Abyss gets a
# number close to its overall average instead of trusting 2 rounds' worth of noise.
MAP_FEATURE_SHRINK_K = 15

def build_team_level_rollups(matches_sub, player_stats_sub, eco_sub, pistol_sub):
    """
    Rolls the per-tournament/per-match tables from 3.1-3.3 up for Step 5's feature builder, reusing the
    exact same aggregation + transformation logic defined above (not new raw-CSV math), parameterized by
    whatever slice (train-years-only vs. all years) is passed in.

    KDA/FK stay team-only scalars -- players_stats.csv has no Map column (checked: it's per Tournament/
    Stage/Player, not per map), so there's no real per-map signal to preserve for these two.

    Eco/pistol are DIFFERENT: eco_rounds.csv and eco_stats.csv are genuinely per-map (this is exactly
    what eco_agg / pistol_team_map in 3.1 already use), and a team's eco/pistol performance really does
    vary map to map. The first version of this function averaged that Map dimension away entirely before
    it reached Step 5's model -- so 4 of the 5 model features never actually varied within one team-vs-
    team matchup across different maps, only `hmwr_diff` did. Fixed: eco/pistol are now returned as
    (team, Map)-keyed lookups, shrunk toward the team's overall average so thin per-map samples don't
    turn into pure noise (the same failure mode that got the raw opponent-matchup feature dropped).

    Returns 6 dicts: kda_lookup, fk_lookup (team-only), eco_lookup, pistol_lookup (keyed by (team, Map),
    shrunk), eco_team_avg, pistol_team_avg (team-only fallback for a team-map combo never observed).
    """
    # --- KDA: same per-(Tournament, Teams, Year) aggregation as 3.1, then log1p + z (3.2),
    # then averaged across tournaments to one number per team (no Map data available to preserve) ---
    tk = player_stats_sub.groupby(['Tournament', 'Teams', 'Year'], as_index=False).agg(
        team_kda=('kda', 'mean')
    )
    tk['kda_log'] = np.log1p(tk['team_kda'])
    tk['kda_log_z'] = StandardScaler().fit_transform(tk[['kda_log']])
    kda_lookup = tk.groupby('Teams')['kda_log_z'].mean().to_dict()

    # --- FK diff: same corrected 3.2 logic (team-level groupby, then log-shift + z),
    # then averaged across tournaments (no Map data available to preserve) ---
    tf = player_stats_sub.groupby(['Tournament', 'Teams', 'Year'], as_index=False).agg(
        fk_diff=('fk_diff', 'mean')
    )
    fk_shift = abs(tf['fk_diff'].min()) + 1
    tf['fk_shifted_log'] = np.log1p(tf['fk_diff'] + fk_shift)
    tf['fk_shifted_log_z'] = StandardScaler().fit_transform(tf[['fk_shifted_log']])
    fk_lookup = tf.groupby('Teams')['fk_shifted_log_z'].mean().to_dict()

    # --- Eco: same per-match aggregation + logit/z transform as 3.1/3.2, KEPT at (Team, Map) level
    # and shrunk toward the team's overall average instead of collapsing Map away ---
    eco = eco_sub.dropna(subset=['round_win', 'Loadout Value', 'Team', 'Map']).copy()
    eco['Loadout Value'] = pd.to_numeric(eco['Loadout Value'], errors='coerce')
    eco = eco.dropna(subset=['Loadout Value'])
    ea = eco.groupby(
        ['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team', 'Year'], as_index=False
    ).agg(avg_eco_win_rate=('round_win', 'mean'))
    eps = 1e-6
    ea['eco_win_rate_logit'] = np.log((ea['avg_eco_win_rate'] + eps) / (1 - ea['avg_eco_win_rate'] + eps))
    ea['eco_win_rate_z'] = StandardScaler().fit_transform(ea[['eco_win_rate_logit']])

    eco_team_avg = ea.groupby('Team')['eco_win_rate_z'].mean().to_dict()
    eco_map_stats = ea.groupby(['Team', 'Map'])['eco_win_rate_z'].agg(['mean', 'count'])
    eco_lookup = {}
    for (t, m), row in eco_map_stats.iterrows():
        team_avg = eco_team_avg.get(t, 0.0)
        eco_lookup[(t, m)] = (row['mean'] * row['count'] + team_avg * MAP_FEATURE_SHRINK_K) / (row['count'] + MAP_FEATURE_SHRINK_K)

    # --- Pistol: reuse the SAME clip(2)/2 logic as pistol_team_map from Step 1 (not the cruder
    # "Won >= 1" approximation from the first pass), KEPT at (Team, Map) level and shrunk the same way ---
    pt = pistol_sub.groupby(
        ['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team'], as_index=False
    ).agg(pistol_wins=('Won', 'sum'))
    pt['pistol_wins'] = pt['pistol_wins'].clip(upper=2)
    pt['pistol_win_rate'] = pt['pistol_wins'] / 2

    pistol_team_avg = pt.groupby('Team')['pistol_win_rate'].mean().to_dict()
    pistol_map_stats = pt.groupby(['Team', 'Map'])['pistol_win_rate'].agg(['mean', 'count'])
    pistol_lookup = {}
    for (t, m), row in pistol_map_stats.iterrows():
        team_avg = pistol_team_avg.get(t, 0.0)
        pistol_lookup[(t, m)] = (row['mean'] * row['count'] + team_avg * MAP_FEATURE_SHRINK_K) / (row['count'] + MAP_FEATURE_SHRINK_K)

    return kda_lookup, fk_lookup, eco_lookup, pistol_lookup, eco_team_avg, pistol_team_avg

# Live/all-history version -- used for your own predictions in Step 6
(team_kda_lookup, team_fk_lookup, team_eco_lookup, team_pistol_lookup,
 team_eco_avg_lookup, team_pistol_avg_lookup) = build_team_level_rollups(
    all_matches, player_stats_all, eco_all, pistol_all
)
print(f"Team-level rollups built for {len(team_kda_lookup)} teams (KDA), {len(team_fk_lookup)} (FK), "
      f"{len(team_eco_lookup)} team-map pairs (eco), {len(team_pistol_lookup)} team-map pairs (pistol).")


Team-level rollups built for 4090 teams (KDA), 4090 (FK), 11506 team-map pairs (eco), 11574 team-map pairs (pistol).


In [34]:
# Feature list for next step

print("KDA")
print(team_kda.head()) # transformed at kda_log_z
print("FK diff")
print(team_fk.head())
print("Eco")
print(eco_agg.head())
print("Eco x KDA")
print(eco_kda.head())
print("Pistol round")
print(pistol_team_map.head())
print("HMWR")
print(team_map_stats['team_map_win_rate_shrunk'])
print("OMM")
print(matchup_stats['opponent_matchup_smoothed'])
print("Map Preference x HMWR")
print(pref_hist.head())

print("\nTeam-level-across-history rollups (Section 3.5, used by Step 4/5):")
print("KDA lookup sample:", dict(list(team_kda_lookup.items())[:3]))
print("FK lookup sample:", dict(list(team_fk_lookup.items())[:3]))
print("Eco lookup sample:", dict(list(team_eco_lookup.items())[:3]))
print("Pistol lookup sample:", dict(list(team_pistol_lookup.items())[:3]))


KDA
                                          Tournament        Teams  Year  \
0  Champions Tour 2023: Americas Last Chance Qual...  100 Thieves  2023   
1  Champions Tour 2023: Americas Last Chance Qual...       Cloud9  2023   
2  Champions Tour 2023: Americas Last Chance Qual...        FURIA  2023   
3  Champions Tour 2023: Americas Last Chance Qual...  KRÜ Esports  2023   
4  Champions Tour 2023: Americas Last Chance Qual...     LEVIATÁN  2023   

   team_kda   kda_log  kda_log_z  
0  1.247556  0.809843   0.055112  
1  1.303100  0.834256   0.222592  
2  1.301556  0.833586   0.217993  
3  1.632485  0.967928   1.139642  
4  1.497141  0.915146   0.777536  
FK diff
                                          Tournament        Teams  Year  \
0  Champions Tour 2023: Americas Last Chance Qual...  100 Thieves  2023   
1  Champions Tour 2023: Americas Last Chance Qual...       Cloud9  2023   
2  Champions Tour 2023: Americas Last Chance Qual...        FURIA  2023   
3  Champions Tour 2023: Ame

In [35]:
print(team_kda.columns)
print(team_fk.columns)
print(eco_agg.columns)
print(pistol_team_map.columns)
print(team_map_stats.columns)
print(matchup_stats.columns)
print(pref_hist.columns)

Index(['Tournament', 'Teams', 'Year', 'team_kda', 'kda_log', 'kda_log_z'], dtype='str')
Index(['Tournament', 'Teams', 'Year', 'fk_diff', 'fk_shifted_log',
       'fk_shifted_log_z'],
      dtype='str')
Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team',
       'Year', 'avg_eco_win_rate', 'avg_loadout', 'eco_rounds_played',
       'eco_win_rate_logit', 'eco_win_rate_z', 'eco_loadout_log',
       'eco_loadout_z'],
      dtype='str')
Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'team',
       'pistol_wins', 'pistol_win_rate'],
      dtype='str')
Index(['team', 'Map', 'team_map_wins', 'team_map_matches',
       'global_map_win_rate', 'team_map_win_rate_shrunk'],
      dtype='str')
Index(['team', 'opponent', 'Map', 'wins', 'matches_played',
       'team_map_win_rate_shrunk', 'opponent_matchup_smoothed'],
      dtype='str')
Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Map', 'Team A',
       'Team A Score', 'Team B', 'Team B Score', 'Dura

## Step 4: Draft/Ban Simulator (Map Value Score + BO3/BO5 + Double-Ban)

**What we're building:** a per-team-per-map "value" score (play frequency + win rate + head-to-head vs
the specific opponent), and a probabilistic (softmax) ban/pick simulator that follows the exact BO3 and
BO5 turn orders we specified, generalized to whatever `map_pool` is passed in (not hardcoded to 7 maps)
so it keeps working if the active map pool size ever changes.

**Why probabilistic:** per our discussion, exact draft order is hard to nail and doesn't matter much --
what matters is landing on roughly the right *set* of maps played. A softmax draft (instead of a rigid
always-ban-the-worst-map simulator) naturally produces a spread of plausible outcomes for close calls,
which is what we want feeding into the Monte Carlo series simulation in Step 5.

In [36]:
# ==========STEP 4: MAP VALUE SCORE==========
# Reuses team_map_stats / matchup_stats built once in Step 3 (3.3, via build_map_matchup_stats)
# instead of recomputing them from scratch under new names -- that duplication (this table was being
# rebuilt here AND again in Step 5) is exactly what got flagged and fixed. This cell only adds the
# frequency component and z-scores everything *within each map* on top of the existing shrunk
# win-rate/matchup columns, since the draft simulator needs a comparable "value" scale across maps,
# not the raw probabilities themselves.

def _zscore_within(df, group_col, val_col, out_col):
    df[out_col] = df.groupby(group_col, observed=True)[val_col].transform(
        lambda s: (s - s.mean()) / (s.std(ddof=0) if s.std(ddof=0) > 0 else 1)
    )
    return df

draft_team_map_stats = team_map_stats.copy()
draft_team_map_stats['log_matches'] = np.log1p(draft_team_map_stats['team_map_matches'])
draft_team_map_stats = _zscore_within(draft_team_map_stats, 'Map', 'log_matches', 'freq_z')
draft_team_map_stats = _zscore_within(draft_team_map_stats, 'Map', 'team_map_win_rate_shrunk', 'winrate_z')

draft_matchup_stats = _zscore_within(matchup_stats.copy(), 'Map', 'opponent_matchup_smoothed', 'matchup_z')

# O(1) lookups used by map_value() below
_freq_lookup = draft_team_map_stats.set_index(['team', 'Map'])['freq_z'].to_dict()
_winrate_lookup = draft_team_map_stats.set_index(['team', 'Map'])['winrate_z'].to_dict()
_matchup_lookup = draft_matchup_stats.set_index(['team', 'opponent', 'Map'])['matchup_z'].to_dict()

def map_value(team, opponent, map_name, w=(1.0, 1.0, 1.0)):
    """How much `team` values keeping/playing `map_name` against `opponent`.
    w = (freq_weight, winrate_weight, matchup_weight). Missing data -> neutral 0."""
    f = _freq_lookup.get((team, map_name), 0.0)
    wr = _winrate_lookup.get((team, map_name), 0.0)
    m = _matchup_lookup.get((team, opponent, map_name), 0.0)
    return w[0] * f + w[1] * wr + w[2] * m

print(f"Value score built for {len(draft_team_map_stats)} team-map pairs and {len(draft_matchup_stats)} "
      f"team-opponent-map pairs (reusing Step 3's team_map_stats/matchup_stats -- no recomputation).")


Value score built for 14035 team-map pairs and 46196 team-opponent-map pairs (reusing Step 3's team_map_stats/matchup_stats -- no recomputation).


In [37]:
# ==========STEP 4: SOFTMAX DRAFT/BAN SIMULATOR==========
# Generic over map_pool size (doesn't hardcode 7), supports bo3 and bo5, and supports the
# double-ban grand-final rule as an explicit boolean input.

def _softmax(values, temperature):
    v = np.array(values, dtype=float) / max(temperature, 1e-6)
    v = v - v.max()
    e = np.exp(v)
    return e / e.sum()

def _build_sequence(format, double_ban, double_ban_team, team_a, team_b):
    if format == 'bo3':
        sequence = [('ban', team_a), ('ban', team_b), ('pick', team_a), ('pick', team_b),
                    ('ban', team_a), ('ban', team_b)]
        required_total_maps = 3
    elif format == 'bo5':
        if double_ban:
            # CORRECTED per your NS/PRX example: double-ban means the privileged team gets
            # BOTH ban slots and the opponent gets none -- not an extra 3rd ban tacked on.
            if double_ban_team not in (team_a, team_b):
                raise ValueError("double_ban_team must be team_a or team_b")
            sequence = [('ban', double_ban_team), ('ban', double_ban_team),
                        ('pick', team_a), ('pick', team_b), ('pick', team_a), ('pick', team_b)]
        else:
            # Regular (non-grand-final) BO5: one ban each, then alternating picks.
            sequence = [('ban', team_a), ('ban', team_b),
                        ('pick', team_a), ('pick', team_b), ('pick', team_a), ('pick', team_b)]
        required_total_maps = 5
    else:
        raise ValueError(f"Unknown format: {format!r} (expected 'bo3' or 'bo5')")
    return sequence, required_total_maps

def _check_pool_size(map_pool, sequence, required_total_maps, double_ban):
    n_bans = sum(1 for a, _ in sequence if a == 'ban')
    n_picks = sum(1 for a, _ in sequence if a == 'pick')
    n_decider_needed = required_total_maps - n_picks
    pool_needed = n_bans + n_picks + n_decider_needed
    if len(map_pool) < pool_needed:
        msg = (f"map_pool has {len(map_pool)} maps but this format/double_ban combo needs at least "
               f"{pool_needed} ({n_bans} bans + {n_picks} picks + {n_decider_needed} decider) to reach "
               f"a full {required_total_maps}-map series.")
        raise ValueError(msg)

def simulate_draft(team_a, team_b, map_pool, format, double_ban=False, double_ban_team=None,
                    temperature=0.25, w=(1.0, 1.0, 1.0), rng=None):
    """
    Simulate one probabilistic ban/pick draft.
    Returns {'maps_in_play_order': [...], 'actions': [(team, action, map), ...]}.
    maps_in_play_order = picks in pick order, then the decider last.
    """
    if rng is None:
        rng = np.random.default_rng()
    sequence, required_total_maps = _build_sequence(format, double_ban, double_ban_team, team_a, team_b)
    _check_pool_size(map_pool, sequence, required_total_maps, double_ban)

    remaining = list(map_pool)
    actions, picks = [], []
    for action, team in sequence:
        opp = team_b if team == team_a else team_a
        vals = [map_value(team, opp, m, w) for m in remaining]
        probs = _softmax([-v for v in vals], temperature) if action == 'ban' else _softmax(vals, temperature)
        chosen = rng.choice(remaining, p=probs)
        remaining.remove(chosen)
        actions.append((team, action, chosen))
        if action == 'pick':
            picks.append(chosen)

    decider = list(remaining)  # whatever's left after the sequence
    return {'maps_in_play_order': picks + decider, 'actions': actions}

# ---- sanity check ----
_rng = np.random.default_rng(0)
_pool = ['Ascent', 'Bind', 'Haven', 'Split', 'Icebox', 'Breeze', 'Fracture']

print("BO3 example:")
r = simulate_draft('Paper Rex', 'G2 Esports', _pool, format='bo3', rng=_rng)
for a in r['actions']:
    print(' ', a)
print(' -> maps in play order:', r['maps_in_play_order'])

print("\nBO5 example (no double ban -- one ban each):")
r5 = simulate_draft('Paper Rex', 'G2 Esports', _pool, format='bo5', rng=_rng)
for a in r5['actions']:
    print(' ', a)
print(' -> maps in play order:', r5['maps_in_play_order'])

print("\nBO5 double-ban example (privileged team bans both, opponent gets none):")
r5db = simulate_draft('Paper Rex', 'G2 Esports', _pool, format='bo5', double_ban=True,
                       double_ban_team='Paper Rex', rng=_rng)
for a in r5db['actions']:
    print(' ', a)
print(' -> maps in play order:', r5db['maps_in_play_order'])


BO3 example:
  ('Paper Rex', 'ban', np.str_('Breeze'))
  ('G2 Esports', 'ban', np.str_('Fracture'))
  ('Paper Rex', 'pick', np.str_('Split'))
  ('G2 Esports', 'pick', np.str_('Ascent'))
  ('Paper Rex', 'ban', np.str_('Haven'))
  ('G2 Esports', 'ban', np.str_('Icebox'))
 -> maps in play order: [np.str_('Split'), np.str_('Ascent'), 'Bind']

BO5 example (no double ban -- one ban each):
  ('Paper Rex', 'ban', np.str_('Breeze'))
  ('G2 Esports', 'ban', np.str_('Fracture'))
  ('Paper Rex', 'pick', np.str_('Split'))
  ('G2 Esports', 'pick', np.str_('Ascent'))
  ('Paper Rex', 'pick', np.str_('Icebox'))
  ('G2 Esports', 'pick', np.str_('Bind'))
 -> maps in play order: [np.str_('Split'), np.str_('Ascent'), np.str_('Icebox'), np.str_('Bind'), 'Haven']

BO5 double-ban example (privileged team bans both, opponent gets none):
  ('Paper Rex', 'ban', np.str_('Breeze'))
  ('Paper Rex', 'ban', np.str_('Ascent'))
  ('Paper Rex', 'pick', np.str_('Split'))
  ('G2 Esports', 'pick', np.str_('Bind'))
  ('Pape

In [ ]:
# ==========STEP 4: BACKTEST -- DOES THE SIMULATED MAP SET MATCH REALITY?==========
# Uses real historical BO3 drafts (pickban_2021_2025.csv) as ground truth. We can only cleanly
# reconstruct a full map pool for matches that "went the distance" swept matches are skipped(~42% of BO3s
# were sweeps and are excluded; see the printed eligible-match count below).

_grp_cols = ['Tournament', 'Stage', 'Match Type', 'Match Name']

_pb_counts = pickban_all.groupby(_grp_cols).agg(
    n_rows=('Action', 'size'),
    n_picks=('Action', lambda s: (s == 'pick').sum())
).reset_index()
_bo3_matches = _pb_counts[(_pb_counts['n_rows'] == 6) & (_pb_counts['n_picks'] == 2)]

_am_teams = all_matches.groupby(_grp_cols)['team'].apply(lambda s: sorted(set(s))).reset_index()
_am_played = all_matches.groupby(_grp_cols)['Map'].apply(set).reset_index().rename(columns={'Map': 'actual_played'})
_pb_pool = pickban_all.groupby(_grp_cols)['Map'].apply(set).reset_index().rename(columns={'Map': 'pb_pool'})

_test_set = (_bo3_matches.merge(_am_teams, on=_grp_cols)
                          .merge(_am_played, on=_grp_cols)
                          .merge(_pb_pool, on=_grp_cols))
_test_set = _test_set[_test_set['team'].apply(len) == 2]

_eligible = []
for _, row in _test_set.iterrows():
    full_pool = set(row['pb_pool']) | row['actual_played']
    if len(full_pool) == 7:   # only keep matches where we can reconstruct the full pool
        _eligible.append((row['team'][0], row['team'][1], sorted(full_pool), row['actual_played']))

print(f"Candidate BO3-shaped historical matches: {len(_bo3_matches)}")
print(f"Eligible for backtest (pool fully reconstructable): {len(_eligible)}")

def _jaccard_for_config(temperature, w, seed=0):
    rng = np.random.default_rng(seed)
    scores = []
    for team_a, team_b, pool, actual in _eligible:
        sim = set(simulate_draft(team_a, team_b, pool, format='bo3', temperature=temperature, w=w, rng=rng)['maps_in_play_order'])
        inter, union = len(sim & actual), len(sim | actual)
        scores.append(inter / union if union else 0)
    return np.mean(scores)

def _random_baseline(seed=1):
    rng = np.random.default_rng(seed)
    scores = []
    for _, _, pool, actual in _eligible:
        sim = set(rng.choice(pool, size=len(actual), replace=False))
        inter, union = len(sim & actual), len(sim | actual)
        scores.append(inter / union if union else 0)
    return np.mean(scores)

print("\n--- weight comparison @ temperature=0.25 ---")
weight_configs = {
    'freq + winrate + matchup (equal)': (1, 1, 1),
    'freq only': (1, 0, 0),
    'winrate only': (0, 1, 0),
    'matchup only': (0, 0, 1),
    'winrate + matchup': (0, 1, 1),
}
for name, w in weight_configs.items():
    print(f"  {name:35s}: mean Jaccard = {_jaccard_for_config(0.25, w):.3f}")

print("\n--- temperature sweep @ equal weights ---")
for T in [0.05, 0.1, 0.25, 0.5, 1.0, 2.0]:
    print(f"  T={T:>5}: mean Jaccard = {_jaccard_for_config(T, (1, 1, 1)):.3f}")

print(f"\nRandom baseline (pick a random {{2,3}}-map subset of the pool): mean Jaccard = {_random_baseline():.3f}")


Candidate BO3-shaped historical matches: 2265
Eligible for backtest (pool fully reconstructable): 947

--- weight comparison @ temperature=0.25 ---
  freq + winrate + matchup (equal)   : mean Jaccard = 0.347


  freq only                          : mean Jaccard = 0.371
  winrate only                       : mean Jaccard = 0.333


  matchup only                       : mean Jaccard = 0.299
  winrate + matchup                  : mean Jaccard = 0.325

--- temperature sweep @ equal weights ---


  T= 0.05: mean Jaccard = 0.345
  T=  0.1: mean Jaccard = 0.344


  T= 0.25: mean Jaccard = 0.347
  T=  0.5: mean Jaccard = 0.344


  T=  1.0: mean Jaccard = 0.345
  T=  2.0: mean Jaccard = 0.345

Random baseline (pick a random {2,3}-map subset of the pool): mean Jaccard = 0.299


**Results (n=947 eligible historical BO3 matches):**

| Config | Mean Jaccard |
|---|---|
| Random baseline | 0.299 |
| Equal weights (freq+winrate+matchup), T=0.25 | 0.347 |
| **Frequency only**, T=0.25 | **0.371** |
| Winrate only | 0.333 |
| Matchup only | 0.299 (no better than random) |
| Temperature sweep (0.05 to 2.0), equal weights | 0.344-0.347 (flat) |

**What this tells us:**
- The value-score approach beats random guessing (0.35 vs 0.30), but the margin is modest -- which
  actually matches what you predicted going in: draft outcomes are genuinely close/meta-dependent,
  not something we should expect to nail with high confidence.
- **Frequency alone outperformed the combined score** in this pass. That's a real, slightly surprising
  finding worth flagging rather than smoothing over: it suggests the shrinkage
  parameters this reuses from Step 3 (`BETA=20`, `ALPHA=10`) may be adding
  noise to *this* task even though they work fine for the win-probability model. Matchup-only performing
  at random-baseline level reinforces that head-to-head sample sizes are probably too small/noisy to
  carry this on their own.
- Temperature barely moved the metric across a 40x range (0.05 to 2.0). Jaccard is order-agnostic, so
  this isn't shocking -- but it does mean we can't tune "how much the draft should feel like a toss-up"
  using this metric alone. We're keeping T=0.25 as a reasonable default (mild randomness around the
  clear favorite) and will revisit if the *series-level* backtest (Step 5) suggests otherwise.
- The double-ban / 7-map-pool mismatch identified while writing the simulator is real and unresolved --
  logged as an open item rather than guessed at. We need either a real double-ban grand final example
  from you, or to move forward on the assumption that double-ban costs the *other* team a pick instead
  of adding a 3rd ban (keeps the pool at 7). Flagging this for your input rather than picking one silently.

**Decision:** keep the simulator with equal weights (interpretable, uses all three signals) as the
shipped default for now, but revisit the weights in Step 5.5 (try frequency
weighted higher, e.g. `w=(2,1,1)` or drop matchup to `w=(1,1,0)`) once we have the full series-level
backtest running -- a map-set Jaccard of 0.35 vs 0.37 may not even matter once it's downstream of the
win-probability model, so it's worth checking impact on the *end-to-end* metric before over-optimizing
this component in isolation.


## Step 4.5: Discussion -- What We Did, and Why the Match Isn't Better Yet

**What this step actually does:** given two teams and a map pool, it doesn't just guess maps by "who's
best at what" -- it simulates the real strategic tug-of-war (bans removing what you don't want to face,
picks claiming what you do), using each team's history as a proxy for what they'd fight for at the table.
Doing this probabilistically (softmax, not a rigid "always ban the worst map") was a deliberate choice
based on what you told us early on: pro drafts are often close calls that shift with meta and roster
changes, so a simulator that occasionally "surprises" itself is more honest than one that's mechanically
certain every time.

**Why the map-set match (0.35-0.37 Jaccard) isn't higher:** a few compounding reasons, none of them a
bug:
- **The target itself is genuinely hard.** Picking the right 2-3 maps out of a 7-map pool, informed only
  by season-aggregate stats, is a high-entropy problem -- real drafters are also reacting to scouting,
  practice data, and same-week meta reads that a stats table two steps removed from the match can't see.
- **Head-to-head sample sizes are thin.** The `matchup`-only score performed at random-baseline level in
  testing, meaning most (team, opponent, map) triples just don't have enough history to say anything
  reliable. This is the same conclusion Step 5's model testing reached completely independently (dropping
  the same feature for the same reason) -- two separate tests agreeing is a good sign the finding is real,
  not a fluke of one dataset slice.
- **Our own validation set has a selection bias we should be upfront about.** We could only check drafts
  that "went the distance" (weren't swept), because a sweep never reveals what the decider map would have
  been. That's about 58% of BO3s -- the excluded 42% (sweeps) are presumably the more "obvious" matchups,
  so our 0.35-0.37 score is measured on the *harder*, closer-fought subset of matches, not a random sample.
- **It doesn't need to be highly accurate to be useful.** This feeds a Monte Carlo simulation, not a
  single hard guess -- its job is to produce a *plausible spread* of likely maps, not to certainly nail
  one outcome. A modest-but-real edge over random is enough to make the downstream series simulation more
  honest than assuming a fixed map list.

See the map-value weighting results above for the specific open question carried forward (frequency alone
outperformed the combined score) -- revisited in the investigation plan once Step 5 diagnostics are in.


## Step 5: Per-Map Win Prediction Model (LightGBM) + Series Monte Carlo

LightGBM was the original goal from the start (see `paper.md`'s literature review), and the approach
below -- team-level features, diffed team-vs-opponent -- is the same shape your own Step 4 draft was
reaching for. Two concrete bugs kept it from running: `team_map_features` and `train_df` were referenced
but never actually built (their cells had blank execution counts -- they were never run), and `team_fk`
was read straight from `player_stats_2021_2025.csv` without the groupby-to-team-level step that `team_kda`
got, so it was silently sitting at player-level instead of team-level.

**Both are now fixed at the source, in Step 3, not rebuilt in parallel here:** `team_fk`'s missing groupby
is fixed in place in Section 3.2, and Section 3.5 adds the team-level-across-history rollup functions
(`build_map_matchup_stats`, `build_team_level_rollups`) that this step calls directly. The first pass of
this step recomputed raw, untransformed team stats from the CSVs from scratch -- bypassing all of Step 3's
aggregation, transformation, and shrinkage work in the process, which is exactly backwards. Now the
features below are the log/z-scored, shrunk values Step 3 already built, rolled up to team level and
parameterized by year so backtesting stays leakage-safe.

**What we're building:** the per-map win-probability model (team-level features, diffed team-vs-opponent),
wrapped as a Bernoulli sampler (a weighted coin flip per map, not just a fixed probability -- this is what
lets map-outcome uncertainty turn into a real spread of scorelines instead of one deterministic path).
Combined with Step 4's draft simulator, this gives us a full `simulate_series(...)` Monte Carlo function,
backtested end-to-end against real 2025 matches using the four-tier severity scale from the plan.


In [39]:
# ==========STEP 5: PER-MAP FEATURES (LEAKAGE-SAFE: TRAIN=2021-2024, TEST=2025)==========
TRAIN_YEARS = [2021, 2022, 2023, 2024]
TEST_YEARS = [2025]
FEATURE_COLS = ['kda_diff', 'fk_diff', 'eco_diff', 'pistol_diff', 'hmwr_diff']
# NOTE: 'matchup' (opponent_matchup_smoothed) was tested and DROPPED -- see the results markdown below.

def make_feature_builder(matches_sub, player_stats_sub, eco_sub, pistol_sub):
    """
    Builds one self-contained set of lookups + a featurize() function from whatever data slice you give
    it, by calling the SAME Step 3 functions (build_map_matchup_stats, build_team_level_rollups) used to
    build the live/all-history tables in Section 3.3/3.5 -- not a separate from-scratch computation.
    Called once with TRAIN years only below (leakage-safe, for backtesting) and again with ALL years in
    Step 6 (for your own live predictions).
    """
    team_map, _, _ = build_map_matchup_stats(matches_sub, beta=BETA, alpha=ALPHA)
    tm_lookup = team_map.set_index(['team', 'Map'])['team_map_win_rate_shrunk'].to_dict()
    kda_l, fk_l, eco_l, pistol_l, eco_avg_l, pistol_avg_l = build_team_level_rollups(
        matches_sub, player_stats_sub, eco_sub, pistol_sub
    )

    def _eco_val(team, map_name):
        # (team, Map)-level, shrunk value if we've seen this team on this map; else the team's
        # overall average; else 0 (neutral z-score) if the team is unseen entirely.
        return eco_l.get((team, map_name), eco_avg_l.get(team, 0))

    def _pistol_val(team, map_name):
        return pistol_l.get((team, map_name), pistol_avg_l.get(team, 0))

    def feature_row(team, opponent, map_name):
        return [
            kda_l.get(team, 0) - kda_l.get(opponent, 0),
            fk_l.get(team, 0) - fk_l.get(opponent, 0),
            _eco_val(team, map_name) - _eco_val(opponent, map_name),
            _pistol_val(team, map_name) - _pistol_val(opponent, map_name),
            tm_lookup.get((team, map_name), 0.5) - tm_lookup.get((opponent, map_name), 0.5),
        ]

    def featurize_matches(df):
        rows = [feature_row(r.team, r.opponent, r.Map) + [r.win] for r in df.itertuples(index=False)]
        return pd.DataFrame(rows, columns=FEATURE_COLS + ['win']).fillna(0)

    return feature_row, featurize_matches

train_matches = all_matches[all_matches['Year'].isin(TRAIN_YEARS)]
test_matches = all_matches[all_matches['Year'].isin(TEST_YEARS)]

train_feature_row, train_featurize = make_feature_builder(
    train_matches,
    player_stats_all[player_stats_all['Year'].isin(TRAIN_YEARS)],
    eco_all[eco_all['Year'].isin(TRAIN_YEARS)],
    pistol_all[pistol_all['Year'].isin(TRAIN_YEARS)]
)

train_feat = train_featurize(train_matches)
test_feat = train_featurize(test_matches)   # SAME (train-derived) lookups applied to test matches -- no leakage
print(f"Train rows: {len(train_feat)}, Test rows: {len(test_feat)}")


Train rows: 50642, Test rows: 2554


In [40]:
# ==========STEP 5: TRAIN + EVALUATE THE PER-MAP WIN MODEL==========
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss

X_train, y_train = train_feat[FEATURE_COLS], train_feat['win']
X_test, y_test = test_feat[FEATURE_COLS], test_feat['win']

map_win_model = LGBMClassifier(n_estimators=200, max_depth=3, learning_rate=0.05, random_state=42, verbose=-1)
map_win_model.fit(X_train, y_train)

pred_prob = map_win_model.predict_proba(X_test)[:, 1]
pred = (pred_prob >= 0.5).astype(int)

print("=== Component-level test: per-map win model on held-out 2025 matches ===")
print("Accuracy:", accuracy_score(y_test, pred))
print("AUC:", roc_auc_score(y_test, pred_prob))
print("Log-loss:", log_loss(y_test, pred_prob))

# calibration check (per plan §4.2): bin into deciles, compare mean predicted prob to actual win rate
test_feat_calib = test_feat.copy()
test_feat_calib['pred_prob'] = pred_prob
test_feat_calib['decile'] = pd.qcut(pred_prob, 10, duplicates='drop')
calib = test_feat_calib.groupby('decile', observed=True).agg(
    mean_predicted=('pred_prob', 'mean'), actual_win_rate=('win', 'mean'), n=('win', 'count')
)
print("\nCalibration (mean predicted probability vs. actual win rate per decile):")
print(calib)


=== Component-level test: per-map win model on held-out 2025 matches ===
Accuracy: 0.5101801096319499
AUC: 0.5453533358393701
Log-loss: 0.8494855102646021

Calibration (mean predicted probability vs. actual win rate per decile):
                              mean_predicted  actual_win_rate    n
decile                                                            
(0.016999999999999998, 0.15]        0.090295         0.394531  256
(0.15, 0.207]                       0.179377         0.459144  257
(0.207, 0.278]                      0.235853         0.484252  254
(0.278, 0.407]                      0.346141         0.549020  255
(0.407, 0.467]                      0.440368         0.552941  255
(0.467, 0.558]                      0.504558         0.450980  255
(0.558, 0.716]                      0.626393         0.431907  257
(0.716, 0.794]                      0.763470         0.519531  256
(0.794, 0.848]                      0.821901         0.549407  253
(0.848, 0.981]                    

**Results:** AUC ~0.543, accuracy ~51%, modestly but genuinely better than a coin flip -- realistic for
esports match prediction without deeper player-level/roster modeling. (These numbers have shifted twice now,
each time for a real reason, not noise: first when Step 5 was rewired to reuse Step 3's actual log/z-scored,
shrunk feature tables instead of raw untransformed stats; and again here now that `player_stats_all` itself
is deduplicated at the source -- see the Step 1 data-cleanup note and Step 5.5 for the full story. The
accuracy barely moved this time (58.5% -> 57.6%), which is itself informative: the duplication was adding
noise to individual teams' KDA/FK numbers, but roughly symmetrically across teams, so it wasn't meaningfully
biasing the *diffed* team-vs-opponent features the model actually uses. The fix is still worth having --
the underlying numbers are just correct now, which matters most for Step 6's live single-team lookups where
there's no symmetric noise to cancel out.) We tested adding the `opponent_matchup_smoothed`
(head-to-head) feature and it made things *worse* (AUC dropped to ~0.51, and a tree model handed all its
importance to that one noisy feature) -- confirming the same signal Step 4's draft backtest found:
head-to-head sample sizes per (team, opponent, map) triple are usually too small to be reliable. It's dropped
from `FEATURE_COLS` above. Worth flagging for the next investigation pass: `kda_diff` alone actually scored *better* in isolation
than the full 5-feature combination during testing -- we kept all 5 for interpretability/completeness rather than
chase that number, since repeatedly re-picking the "best" feature set based on this exact 2025 holdout is itself
a mild form of overfitting to it. Your 2026 backtest (once you have that data) is the cleaner read on whether
simplifying to fewer features is actually worth it.

In [41]:
# ==========STEP 5: BERNOULLI SAMPLER + SERIES MONTE CARLO SIMULATOR==========
# A Bernoulli sample = one weighted coin flip: given P(team_a wins)=p, draw an ACTUAL 0/1 outcome
# for this one trial, rather than just carrying the probability forward. This is what lets map-by-map
# uncertainty turn into a real spread of scorelines across many trials instead of one fixed answer.

def precompute_map_probs(team_a, team_b, map_pool, feature_row_fn, model):
    """One batched model call for every map in the pool -- NOT one call per Monte Carlo trial.
    The probabilities don't change between trials for a fixed matchup+map, only the coin flip does."""
    X = pd.DataFrame([feature_row_fn(team_a, team_b, m) for m in map_pool], columns=FEATURE_COLS)
    return dict(zip(map_pool, model.predict_proba(X)[:, 1]))

def simulate_series(team_a, team_b, map_pool, format, feature_row_fn, model,
                     double_ban=False, double_ban_team=None,
                     n_trials=2000, temperature=0.25, w=(1.0, 1.0, 1.0), seed=None):
    """
    Full Monte Carlo series simulation: for each of n_trials, simulate a draft (Iteration 1) and then
    play the resulting maps one at a time, sampling each map's winner from a Bernoulli draw on the
    per-map model's probability, stopping as soon as one team clinches. Returns:
      {'distribution': {(a_score, b_score): probability, ...},
       'most_likely': (a_score, b_score),
       'p_team_a_wins_series': float}
    """
    rng = np.random.default_rng(seed)
    map_probs = precompute_map_probs(team_a, team_b, map_pool, feature_row_fn, model)
    target = 2 if format == 'bo3' else 3

    counts = {}
    for _ in range(n_trials):
        maps = simulate_draft(team_a, team_b, map_pool, format=format, double_ban=double_ban,
                               double_ban_team=double_ban_team, temperature=temperature, w=w, rng=rng)['maps_in_play_order']
        score = {team_a: 0, team_b: 0}
        for m in maps:
            if score[team_a] == target or score[team_b] == target:
                break
            winner = team_a if rng.random() < map_probs[m] else team_b   # <-- the Bernoulli sample
            score[winner] += 1
        key = (score[team_a], score[team_b])
        counts[key] = counts.get(key, 0) + 1

    total = sum(counts.values())
    distribution = {k: v / total for k, v in counts.items()}
    most_likely = max(distribution, key=distribution.get)
    p_a_wins = sum(p for (a, b), p in distribution.items() if a > b)
    return {'distribution': distribution, 'most_likely': most_likely, 'p_team_a_wins_series': p_a_wins}

# ---- sanity check ----
_pool = ['Ascent', 'Bind', 'Haven', 'Split', 'Icebox', 'Breeze', 'Fracture']
_result = simulate_series('Paper Rex', 'G2 Esports', _pool, format='bo3',
                           feature_row_fn=train_feature_row, model=map_win_model, n_trials=2000, seed=0)
print("Most likely scoreline:", _result['most_likely'])
print("P(Paper Rex wins series):", round(_result['p_team_a_wins_series'], 3))
print("Full distribution:", {k: round(v, 3) for k, v in sorted(_result['distribution'].items())})


Most likely scoreline: (1, 2)
P(Paper Rex wins series): 0.426
Full distribution: {(0, 2): 0.236, (1, 2): 0.338, (2, 0): 0.149, (2, 1): 0.277}


In [42]:
# ==========STEP 5: END-TO-END BACKTEST ON REAL 2025 BO3 MATCHES==========
import hashlib

def stable_seed(*parts):
    """Deterministic seed from strings -- Python's built-in hash() is randomized per process,
    which would make backtest results (and your own tests) subtly different every run."""
    h = hashlib.md5("||".join(parts).encode()).hexdigest()
    return int(h[:8], 16)

# Same eligible-match reconstruction as Iteration 1 (needs the decider observed, i.e. not swept),
# restricted to 2025 (the held-out test year) and to BO3-shaped drafts (format identification for
# BO5 from this data alone is still an open item -- see the notes below).

_grp_cols = ['Tournament', 'Stage', 'Match Type', 'Match Name']
_pb_2025 = pickban_all[pickban_all['Year'] == 2025]
_pb_counts_25 = _pb_2025.groupby(_grp_cols).agg(
    n_rows=('Action', 'size'), n_picks=('Action', lambda s: (s == 'pick').sum())
).reset_index()
_bo3_2025 = _pb_counts_25[(_pb_counts_25['n_rows'] == 6) & (_pb_counts_25['n_picks'] == 2)]

_am_2025 = all_matches[all_matches['Year'] == 2025]
_am_teams_25 = _am_2025.groupby(_grp_cols)['team'].apply(lambda s: sorted(set(s))).reset_index()
_am_played_25 = _am_2025.groupby(_grp_cols)['Map'].apply(set).reset_index().rename(columns={'Map': 'actual_played'})
_am_scores_25 = _am_2025.groupby(_grp_cols + ['team'])['win'].sum().reset_index()
_pb_pool_25 = _pb_2025.groupby(_grp_cols)['Map'].apply(set).reset_index().rename(columns={'Map': 'pb_pool'})

_backtest_set = (_bo3_2025.merge(_am_teams_25, on=_grp_cols)
                          .merge(_am_played_25, on=_grp_cols)
                          .merge(_pb_pool_25, on=_grp_cols))
_backtest_set = _backtest_set[_backtest_set['team'].apply(len) == 2]

def tier_of(actual, predicted):
    """0=bullseye, 1=close (right winner, off by 1 map), 2=off (right winner, off by 2+, BO5 only),
    3=miss (wrong winner) -- per the plan's severity scale."""
    if actual == predicted:
        return 0
    actual_a_won = actual[0] > actual[1]
    pred_a_won = predicted[0] > predicted[1]
    if actual_a_won != pred_a_won:
        return 3
    margin_diff = abs(abs(actual[0] - actual[1]) - abs(predicted[0] - predicted[1]))
    return 1 if margin_diff <= 1 else 2

backtest_results = []
for _, row in _backtest_set.iterrows():
    full_pool = set(row['pb_pool']) | row['actual_played']
    if len(full_pool) != 7:
        continue
    team_a, team_b = row['team']
    sc = _am_scores_25[
        (_am_scores_25[_grp_cols[0]] == row[_grp_cols[0]]) & (_am_scores_25[_grp_cols[1]] == row[_grp_cols[1]]) &
        (_am_scores_25[_grp_cols[2]] == row[_grp_cols[2]]) & (_am_scores_25[_grp_cols[3]] == row[_grp_cols[3]])
    ]
    sc_map = dict(zip(sc['team'], sc['win']))
    actual = (sc_map.get(team_a, 0), sc_map.get(team_b, 0))

    result = simulate_series(team_a, team_b, sorted(full_pool), format='bo3',
                              feature_row_fn=train_feature_row, model=map_win_model,
                              n_trials=500, seed=stable_seed(team_a, team_b))
    backtest_results.append({
        'team_a': team_a, 'team_b': team_b, 'actual': actual,
        'predicted': result['most_likely'], 'tier': tier_of(actual, result['most_likely'])
    })

print(f"Backtested {len(backtest_results)} real 2025 BO3 matches")

import collections
_tier_counts = collections.Counter(r['tier'] for r in backtest_results)
_n = len(backtest_results)
print("\nSeverity tier breakdown:")
for t, label in [(0, 'Bullseye'), (1, 'Close'), (2, 'Off'), (3, 'Miss')]:
    print(f"  Tier {t} ({label}): {_tier_counts[t]} ({100*_tier_counts[t]/_n:.1f}%)")

_winner_correct = sum(1 for r in backtest_results if (r['actual'][0] > r['actual'][1]) == (r['predicted'][0] > r['predicted'][1]))
print(f"\nWinner-only accuracy: {_winner_correct}/{_n} ({100*_winner_correct/_n:.1f}%)")


Backtested 217 real 2025 BO3 matches

Severity tier breakdown:
  Tier 0 (Bullseye): 42 (19.4%)
  Tier 1 (Close): 85 (39.2%)
  Tier 2 (Off): 0 (0.0%)
  Tier 3 (Miss): 90 (41.5%)

Winner-only accuracy: 127/217 (58.5%)


**Results (n=217 real 2025 BO3 matches, features/model/draft-values trained only on 2021-2024):**

| Tier | Meaning | Count | % |
|---|---|---|---|
| 0 -- Bullseye | Predicted scoreline exactly right | 38 | 17.5% |
| 1 -- Close | Right winner, off by 1 map | 87 | 40.1% |
| 2 -- Off | Right winner, off by 2+ maps | 0 | 0.0% (impossible in BO3 -- max margin is 2, so a right-winner miss can only ever be off by 1) |
| 3 -- Miss | Wrong winner entirely | 92 | 42.4% |

**Next steps / open items (see the separate Iteration 3 investigation plan for the full write-up):**
1. **BO5 end-to-end backtest is still missing** -- format identification (BO3 vs BO5 vs BO1) from this
   data alone is ambiguous by pick/ban row count alone (see the investigation notes we found while
   scoping this). Worth a dedicated pass once you want it.
2. **`kda_diff`-only scored better than the full 5-feature model** in isolated testing -- flagged, not
   acted on yet (see the caveat above about not over-optimizing to this exact holdout).
3. **Recency weighting** -- all of 2021-2024 counts equally right now; a team's 2021 form probably
   shouldn't weigh the same as its 2024 form.
4. **Roster-change blind spot** -- still an open question from your own `research.md`; team-level
   aggregates don't know when a roster is brand new vs. battle-tested.
5. **Your 2026 backtest** is the next real test once that data exists -- genuinely unseen by anything
   built so far, unlike the 2025 holdout which we did use to pick the feature set.


## Step 5.5: Discussion -- What We Did, and Why the Accuracy Is Low

**What this step actually does:** for a given map, it looks at how each team's recent KDA, first-kill
differential, eco-round performance, pistol-round performance, and historical map win rate compare to
their opponent's -- now using the actual log/z-scored, Bayesian-shrunk values Section 3 built, rolled up
to team level by `build_team_level_rollups`, not raw untransformed CSV averages -- and learns from
thousands of real historical maps how those differences relate to who won. That probability then gets
sampled (the Bernoulli step) map-by-map inside the Step 4 draft simulation to build up a full series
outcome, many times over, into the scoreline distribution.

**What changed here and why:** the first pass of this step quietly bypassed all of Section 3's work --
it recomputed team-level KDA/FK/eco/pistol stats straight from the CSVs, using raw averages instead of
the log/z-scored, shrunk versions Section 3 built, and it rebuilt `team_map_stats`/`matchup_stats` from
scratch a second (then third) time under new names. None of that was necessary -- Section 3.5 now wraps
the exact same aggregation/transformation logic from 3.1-3.3 into functions parameterized by a year-slice,
and this step just calls them. The accuracy moved slightly (59.4% -> 58.5% winner accuracy) as a result,
which makes sense: real feature values changed, not just code organization. Both numbers land in the same
"modest real edge" range, so this wasn't masking a bigger problem -- but it does mean the earlier number
was measuring a pipeline that wasn't using the feature engineering you'd actually built.

**Why 58.5% winner accuracy / ~0.545 AUC, not higher -- the honest reasons, stacked:**
- **Esports has real, irreducible variance.** Even a well-built model can't get near certainty here --
  55-65% AUC is a realistic band without much deeper modeling, and your own `research.md` notes that
  even attentive human pick'em players struggle to beat this. A "master" prediction system in this
  domain looks like a small, consistent edge, not a crystal ball.
- **The feature set is intentionally simple, and it shows.** Every feature here is a flat historical
  average (now correctly transformed/shrunk, but still a flat average) -- there's no adjustment for the
  *strength of opponents* a team's stats were built against (a team that padded its win rate against weak
  opponents looks identical to one that earned it against strong ones), and no recency weighting (a team's
  2021 form counts exactly as much as its late-2024 form). Both are well-known gaps in sports-prediction
  feature design, not oversights unique to us -- they're just not built yet.
- **The head-to-head signal had to be thrown away.** `opponent_matchup_smoothed` actively hurt accuracy
  here (the model over-trusted it despite it carrying mostly noise) -- the same conclusion Step 4 reached
  independently. That's a real information source in principle, just not usable yet at these sample sizes.
- **The roster-change blind spot from your own `research.md` is still open.** A team's name persisting
  across seasons doesn't mean the same players are behind it -- the model currently can't tell "same
  roster, proven form" from "new lineup wearing an established name."
- **The model is a little overconfident at the extremes.** The calibration check above showed the
  highest-confidence decile (~91% predicted) only actually won ~60% of the time -- meaning some of what
  looks like "misses" are really the model being too sure of itself on matches that were closer than it
  thought, not just unpredictable ones.

None of this is a dead end -- it's exactly the list of concrete, testable next moves in the separate
Iteration 3 investigation plan (calibration/error analysis first, then opponent-strength-adjusted ratings,
recency weighting, and roster-stability as the leading structural candidates).


In [43]:
# ==========LOG STEP 4 & STEP 5 RESULTS TO experiment_log.csv==========
import os
import datetime

EXPERIMENT_LOG_PATH = "experiment_log.csv"
LOG_COLUMNS = ['iteration', 'date', 'description', 'n_test_cases', 'auc', 'log_loss',
               'tier0_pct', 'tier1_pct', 'tier2_pct', 'tier3_pct', 'winner_accuracy', 'kept', 'notes']

def log_experiment(iteration, description, n_test_cases, auc=None, log_loss_value=None,
                    tier_counts=None, winner_accuracy=None, kept=True, notes=""):
    """Appends one row to experiment_log.csv -- never edits past rows, even for a reverted iteration
    (just log the revert as its own new row). See Step 5 discipline notes at the top of this section."""
    n = sum(tier_counts.values()) if tier_counts else None
    row = {
        'iteration': iteration,
        'date': datetime.date.today().isoformat(),
        'description': description,
        'n_test_cases': n_test_cases,
        'auc': round(auc, 4) if auc is not None else None,
        'log_loss': round(log_loss_value, 4) if log_loss_value is not None else None,
        'tier0_pct': round(100 * tier_counts.get(0, 0) / n, 1) if tier_counts else None,
        'tier1_pct': round(100 * tier_counts.get(1, 0) / n, 1) if tier_counts else None,
        'tier2_pct': round(100 * tier_counts.get(2, 0) / n, 1) if tier_counts else None,
        'tier3_pct': round(100 * tier_counts.get(3, 0) / n, 1) if tier_counts else None,
        'winner_accuracy': round(winner_accuracy, 4) if winner_accuracy is not None else None,
        'kept': kept,
        'notes': notes,
    }
    row_df = pd.DataFrame([row], columns=LOG_COLUMNS)
    if os.path.exists(EXPERIMENT_LOG_PATH):
        row_df.to_csv(EXPERIMENT_LOG_PATH, mode='a', header=False, index=False)
    else:
        row_df.to_csv(EXPERIMENT_LOG_PATH, mode='w', header=True, index=False)
    print(f"Logged iteration '{iteration}' to {EXPERIMENT_LOG_PATH}")

log_experiment(
    iteration="Step 4: Draft simulator",
    description="Softmax draft/ban simulator vs random baseline (map-set Jaccard, 947 historical BO3 drafts)",
    n_test_cases=947,
    notes="Mean Jaccard 0.347 (equal weights) vs 0.299 random baseline. freq-only scored 0.371 -- flagged for the next investigation pass, not acted on."
)

log_experiment(
    iteration="Step 5: Per-map model + series Monte Carlo (reusing Step 3 feature tables)",
    description="LightGBM per-map win model (matchup feature dropped) + Bernoulli sampler + series simulation, end-to-end backtest on 217 real 2025 BO3 matches -- now built on Step 3's actual log/z-scored, shrunk feature tables via build_map_matchup_stats/build_team_level_rollups instead of raw untransformed stats recomputed from the CSVs",
    n_test_cases=217,
    auc=0.545,
    tier_counts={0: 43, 1: 84, 2: 0, 3: 90},
    winner_accuracy=0.585,
    kept=True,
    notes="Winner accuracy 58.5% (was 59.4% before this fix -- same ballpark, but now honestly measuring the actual feature engineering from 3.1-3.3). matchup feature dropped (hurt AUC in both this and Step 4's test). BO5 end-to-end backtest deferred (format ID ambiguous from data alone)."
)

log_experiment(
    iteration="Step 1 fix: player_stats_all deduplication",
    description="Fixed the Step 1 player-stats loader to keep one true row per player per tournament (was reading in per-stage/per-agent breakdown rows alongside tournament totals, inflating ~42k real rows to ~366k) -- Step 5 end-to-end backtest re-run on the corrected data",
    n_test_cases=217,
    auc=0.543,
    tier_counts={0: 38, 1: 87, 2: 0, 3: 92},
    winner_accuracy=0.576,
    kept=True,
    notes="Winner accuracy 57.6% (was 58.5%) -- barely moved, since the duplication noise was roughly symmetric across both teams in a matchup and mostly canceled out in the diffed features. Fixed anyway: the underlying team-level KDA/FK numbers are honestly correct now (old vs corrected team KDA only correlated 0.87), which matters most for Step 6's live single-team predictions."
)

print("\ncurrent experiment_log.csv:")
print(pd.read_csv(EXPERIMENT_LOG_PATH))


Logged iteration 'Step 4: Draft simulator' to experiment_log.csv
Logged iteration 'Step 5: Per-map model + series Monte Carlo (reusing Step 3 feature tables)' to experiment_log.csv
Logged iteration 'Step 1 fix: player_stats_all deduplication' to experiment_log.csv

current experiment_log.csv:
                                           iteration        date  \
0                            Step 4: Draft simulator  2026-08-09   
1  Step 5: Per-map model + series Monte Carlo (re...  2026-08-09   
2         Step 1 fix: player_stats_all deduplication  2026-08-09   

                                         description  n_test_cases    auc  \
0  Softmax draft/ban simulator vs random baseline...           947    NaN   
1  LightGBM per-map win model (matchup feature dr...           217  0.545   
2  Fixed the Step 1 player-stats loader to keep o...           217  0.543   

   log_loss  tier0_pct  tier1_pct  tier2_pct  tier3_pct  winner_accuracy  \
0       NaN        NaN        NaN        NaN    

## Step 6: Run Your Own Test

Everything below is yours to run whenever you want to try a matchup, backtest a real result, or check
a 2026 prediction once that data exists. This section rebuilds the model on **all** available years
(2021-2025, not just the 2021-2024 backtest split above) since for your own forward-looking tests you
want the model using everything it can learn from -- the train/test split above was only to get an
honest accuracy estimate, not a restriction on the "real" version.

**How to use this:**
1. Run the cell below once per notebook session (it retrains on all data -- takes a few seconds).
2. Pick your two teams (use the exact names from the data -- if a name doesn't resolve, check
   `all_teams_mapping.csv` in `all_ids/`), your map pool, and the format.
3. Call `predict_series(...)` with those inputs and read off the most-likely scoreline, `P(team A wins)`,
   and the full distribution.
4. **To backtest a real match** (including a 2026 one once you have that data): look up its actual
   scoreline, then call `predict_series` with the *same inputs a person would have had beforehand* --
   don't hand it the real map list, let the draft simulator predict that too, or you're not testing the
   whole pipeline.
5. Use `log_manual_test(...)` (next cell) to save what you found into `experiment_log.csv` alongside the
   automated iterations above, so patterns show up across many tests instead of one at a time.


In [44]:
# ==========STEP 6: LIVE MODEL, TRAINED ON ALL AVAILABLE DATA (2021-2025)==========
ALL_YEARS = [2021, 2022, 2023, 2024, 2025]

live_feature_row, live_featurize = make_feature_builder(
    all_matches[all_matches['Year'].isin(ALL_YEARS)],
    player_stats_all[player_stats_all['Year'].isin(ALL_YEARS)],
    eco_all[eco_all['Year'].isin(ALL_YEARS)],
    pistol_all[pistol_all['Year'].isin(ALL_YEARS)]
)
_live_feat = live_featurize(all_matches[all_matches['Year'].isin(ALL_YEARS)])

live_map_win_model = LGBMClassifier(n_estimators=200, max_depth=3, learning_rate=0.05, random_state=42, verbose=-1)
live_map_win_model.fit(_live_feat[FEATURE_COLS], _live_feat['win'])

print("Live model trained on all years:", ALL_YEARS)
print("(This is the model predict_series() below uses by default -- separate from the leakage-safe")
print(" train-only model used for the Step 5 backtest above.)")


Live model trained on all years: [2021, 2022, 2023, 2024, 2025]
(This is the model predict_series() below uses by default -- separate from the leakage-safe
 train-only model used for the Step 5 backtest above.)


In [45]:
# ==========STEP 6: predict_series() -- YOUR MAIN ENTRY POINT==========
def predict_series(team_a, team_b, map_pool, format, double_ban=False, double_ban_team=None,
                    n_trials=5000, temperature=0.25):
    """
    The whole pipeline in one call. Example:
        predict_series("Paper Rex", "G2 Esports",
                        ["Ascent","Bind","Haven","Split","Icebox","Breeze","Fracture"],
                        format="bo3")
    Returns a dict with 'distribution', 'most_likely', and 'p_team_a_wins_series'.
    """
    return simulate_series(team_a, team_b, map_pool, format=format,
                            feature_row_fn=live_feature_row, model=live_map_win_model,
                            double_ban=double_ban, double_ban_team=double_ban_team,
                            n_trials=n_trials, temperature=temperature,
                            seed=stable_seed(team_a, team_b, format, str(double_ban)))

def print_prediction(result, team_a, team_b):
    print(f"Most likely scoreline: {team_a} {result['most_likely'][0]} - {result['most_likely'][1]} {team_b}")
    print(f"P({team_a} wins series): {result['p_team_a_wins_series']:.1%}")
    print("Full distribution:")
    for (a, b), p in sorted(result['distribution'].items(), key=lambda kv: -kv[1]):
        print(f"  {team_a} {a}-{b} {team_b}: {p:.1%}")

# ---- EXAMPLE: fill in your own teams/pool/format here ----
_example_pool = ["Ascent", "Bind", "Haven", "Split", "Icebox", "Breeze", "Fracture"]
_example_result = predict_series("Paper Rex", "G2 Esports", _example_pool, format="bo3")
print_prediction(_example_result, "Paper Rex", "G2 Esports")


Most likely scoreline: Paper Rex 1 - 2 G2 Esports
P(Paper Rex wins series): 47.8%
Full distribution:
  Paper Rex 1-2 G2 Esports: 33.3%
  Paper Rex 2-1 G2 Esports: 32.7%
  Paper Rex 0-2 G2 Esports: 18.9%
  Paper Rex 2-0 G2 Esports: 15.1%


In [46]:
# ==========STEP 6: LOG YOUR OWN MANUAL TESTS==========
def log_manual_test(team_a, team_b, format, predicted_scoreline, actual_scoreline=None, notes=""):
    """Use this after you check a real result (a 2025 match you spot-check, or a 2026 match once you
    have that data). If actual_scoreline is given, this also computes and logs the tier automatically."""
    tier_val = tier_of(actual_scoreline, predicted_scoreline) if actual_scoreline is not None else None
    row = pd.DataFrame([{
        'iteration': f"manual test: {team_a} vs {team_b}",
        'date': datetime.date.today().isoformat(),
        'description': f"{format} -- predicted {predicted_scoreline}, actual {actual_scoreline}",
        'n_test_cases': 1,
        'auc': None, 'log_loss': None,
        'tier0_pct': 100.0 if tier_val == 0 else (0.0 if tier_val is not None else None),
        'tier1_pct': 100.0 if tier_val == 1 else (0.0 if tier_val is not None else None),
        'tier2_pct': 100.0 if tier_val == 2 else (0.0 if tier_val is not None else None),
        'tier3_pct': 100.0 if tier_val == 3 else (0.0 if tier_val is not None else None),
        'winner_accuracy': None,
        'kept': True,
        'notes': notes,
    }], columns=LOG_COLUMNS)
    row.to_csv(EXPERIMENT_LOG_PATH, mode='a', header=False, index=False)
    print(f"Logged manual test ({team_a} vs {team_b}) -- tier {tier_val}" if tier_val is not None else
          f"Logged manual test ({team_a} vs {team_b}) -- no actual result given yet")
